### ISSUE TITLE
Improve "Wrapping Up" Section of Tutorial

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#118]
@cannikin what do you think about improvements like these to the last section?

## Wrapping Up
..current text and pat on the back. Plus emojis. Lots of emojis.

### Next Steps: Improve your App
Recommend some guides and tutorials to make their app better:
- cookbook on 3rd party API
- guide on installing Postgres locally
- etc

### Next Steps: Joining the Community
...what you currently have, but maybe highlight each with a sentence explanation

### RedwoodJS Roadmap
1. Auth (link to tracking Issue)
2. TypeScript (link to tracking Issue)
3. Testing (link to tracking Issue)
4. Storybook (link to tracking Issue)

...everything else. Here's a list I copied from Tom's notes last month:

- Accessibility features for Redwood Router
- Switcher widget (website, GraphQL playground) in dev mode
- Cookbook of recipes for integrating 3rd party APIs
- Easy way to inspect logs from AWS Lambda
- Storybook integration
- Refine Jest integration
- Data fetching optimization to solve for the waterfall problem

**Comment by cannikin** [comment]
Yup I like all of this! I tend to not use emojis when writing docs (personal preference), but I'll be happy to review any PR that includes some. 😉

I'll work on this tomorrow!

**Comment by cannikin** [comment]
@thedavidprice Let me know how that looks and if I linked to the correct issues for those 4 features!

**Comment by thedavidprice** [comment]
🚀
(emoji use intentional)

Looks super great to me, RC. Thanks for taking the time! We should probably get TPWs eyes on the Roadmap -- I'll ping him directly.

>Even those of us working on the framework are heading over to Google multiple times per day to figure out how to get these things to work together.

In my case, replace "multiple" with "multitude"... 😬
