### ISSUE TITLE
auto-publish new News (and other) items to Twitter

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#121]
If simple, it would be nice to have news and other updates auto-distributing. Just close this out if it seems like there'd be too much work involved. We can handle it via manual process just as well.

**Comment by cannikin** [comment]
HMMM Shouldn't be too bad with their API, but I'm usually a couple of days behind on new news launching, do we care if we've already announced it via Twitter when it actually happens, then the site announces it again via the API a couple of days later?

I dunno if we have enough news right now to make the dev investment worth it...I'm maybe adding 1 news item a week.

**Comment by thedavidprice** [comment]
re: redundant tweets -- I don't think it would be an issue as most accounts post about a topic several times.

But I think you're right on the "not yet worth it" side of things right now. Let's just try to keep Twitter in mind adding things like new docs, Videos, Cookbooks, news, etc. manually to the Twitter feed. 

I'm fine with that. closing this.
