### ISSUE TITLE
Add note about upgrading to 0.6.0 in the Auth section

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#141]
A lot of users seem to be getting stuck adding Auth because they didn't realize they needed to upgrade to at least 0.7.0. Let's add a little callout a the top of the Authentication section of the tutorial to remind them.

**Comment by thedavidprice** [comment]
Thanks! I think the root cause is me sending a lot of people directly to the Auth section via my forum topic and release note links. 

But, you know, that'll learn 'em.

¯\_(ツ)_/¯
