### ISSUE TITLE
Add Discord link to header/footer

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#153]

**Comment by thedavidprice** [comment]
I'm looking into Discord "setting" now:
- add an overview message or description about purpose
- add a link/widget to "start new thread in forum"

**Draft Copy (please help shape):**
Welcome to the official Redwood Discord server. Consider this the community "watercooler" -- a place for getting to know each other, discussing related topics (and sometimes tangential), and sharing your interests. tl;dr: this is the place for cultivating relationships! So, how is it different than the Redwood Forums? We use the forums for helping each other, contributing, and discussing foundation Redwood concepts that need focus and _permanance_. tl;dr: the forums are our community knowledgebase! If you find yourself here in Discord talking about how to solve a Redwood problem or sharing a new project, please do move that to the Forums (and vice-versa). Lastly, if you haven't already read our community guidelines, please do as they'll be closely held to create an awesome culture everywhere.
