### ISSUE TITLE
Add tooltips to header channels

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#154]
So people get a sense of what kind of content goes where.

Discourse: for long form discussions, show & tell
Discord: quick questions and feedback

**Comment by cannikin** [comment]
![image](https://user-images.githubusercontent.com/300/83311795-233c3900-a1c5-11ea-9f73-6d8eb35843e2.png)

![image](https://user-images.githubusercontent.com/300/83311804-29321a00-a1c5-11ea-8177-f35af8bc58f1.png)

**Comment by cannikin** [comment]
How are these for descriptions @thedavidprice @mojombo

**Comment by thedavidprice** [comment]
Just iterating here. Tried Knowledgebase. I like it, but mabye it feels too "cold"? Could Knowledge Repo be a (better) thing?

Redwood's Knowledge-Repo: discussions, how-to, troubleshooting, show & tell

Redwood's Watercooler: relationship building, chats, and #random

**Comment by cannikin** [comment]
I think of a more formal thing when I think of Knowledge Base, like a searchable collection of FAQs on a product site. And "repo" kind of confuses with GitHub repo maybe?
