### ISSUE TITLE
Code Copy button loses line breaks

### ISSUE THREAD

**Issue by sgarrity** [redwoodjs/redwoodjs.com#158]
When copying the sample code from the [Back Home section on the tutorial](https://redwoodjs.com/tutorial/a-second-page-and-a-link#back-home), the code is copied without line breaks in the JSX portion.

The copied code looks like this:
```
import { Link, routes } from '@redwoodjs/router'
const AboutPage = () => {
  return (
    <>      <header>        <h1>Redwood Blog</h1>        <nav>          <ul>            <li>              <Link to={routes.about()}>About</Link>            </li>          </ul>        </nav>      </header>      <main>        <p>          This site was created to demonstrate my mastery of Redwood: Look on my          works, ye mighty, and despair!        </p>        <Link to={routes.home()}>Return home</Link>      </main>    </>  )
}

export default AboutPage
``` 

Instead of looking like this: 
<img width="679" alt="image" src="https://user-images.githubusercontent.com/58062/83341636-e2731b80-a2bb-11ea-981d-afeaafcce087.png">

**Comment by jtoar** [comment]
@sgarrity Thanks for pointing this out, I'll look into it!

**Comment by sgarrity** [comment]
Works great. Thanks, y'all!
