### ISSUE TITLE
Tutorial: Side Quest apollo clarification

### ISSUE THREAD

**Issue by dardub** [redwoodjs/redwoodjs.com#159]
On the following page: https://redwoodjs.com/tutorial/side-quest-how-redwood-works-with-data

Back to our data flow: Apollo has called the resolver which, in our case, retrieved data from the database. Apollo digs into the object and returns only the key/values that were asked for in the GraphQL query. It then packages up the response in a GraphQL payload and returns it to the browser.

Do you guys think it's clear in this paragraph whether it's referring to Apollo Server or Apollo Client?

Thanks!

**Comment by jtoar** [comment]
Hey thanks for bringing this up! I totally see your point here.

I think it's pretty clear: we say "called the resolver" shortly after "Apollo", which implies that this is the Apollo Server (and if I got that wrong, then yikes!). Then we end that paragraph with "returns it to the browser", so we can be pretty sure that we're not talking about the client at this point.

But we could've avoided all that by just saying it's the Apollo Server. And I don't think changing Apollo to Apollo Server would make this sentence any less readable--anywhere we can be more explicit w/o muddling prose we should. So I'd say throw up a PR!

One question: are the other three references confusing too?

> Normally you would write a resolver map that contains all your resolvers and tells Apollo how to map them to your SDL.

> They will usually get your data from a database, but they can do anything you want, as long as they return the proper types that Apollo expects based on what you defined in posts.sdl.js.

> Apollo assumes these functions return promises, which db (an instance of PrismaClient) does. Apollo waits for them to resolve before responding with your query results, so you don't need to worry about async/await or mess with callbacks yourself.

**Comment by dardub** [comment]
@jtoar I think from the perspective of someone who has little Apollo experience it could create more confusion. If you don't think it's over-kill to be more explicit everywhere, I can make that PR.

**Comment by jtoar** [comment]
@dardub I say go for it!

**Comment by cannikin** [comment]
We'd love to see a PR that clarifies this, thanks!

**Comment by jtoar** [comment]
Hey @dardub, just wanted to see if you were still interested in this one. The api side has come up a lot recently on the forum, and I think a clarification like this is just what we need.
