### ISSUE TITLE
Links in the "On this page" nav are (kind of) broken

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwoodjs.com#169]
The links in the "On this page" nav seem kind of broken. Easiest to see with the [CLI Commands](https://redwoodjs.com/docs/cli-commands) page. The behavior I'm seeing is that when the url is 

```
https://redwoodjs.com/docs/cli-commands
```

You can use any link in the on "On this page" nav once, but then all other links take you back to the top/just don't work.

Can't point to exactly how yet but things seem to have broken with [dea43619d7d6a5b7afc415626bc381073b6a5f4f](https://github.com/redwoodjs/redwoodjs.com/commit/dea43619d7d6a5b7afc415626bc381073b6a5f4f); checking-out the one before it gives the expected behavior. I'll try to diagnose.

**Comment by cannikin** [comment]
Yeah it seems like any anchor link stops working after the first click. It could be that my code that resets the scroll position to get you past the top nav is always being invoked, even when there isn't a new page load. Either the `turbolinks:before-cache` event is firing when clicking those links, or the code that figures out which nav item should be open and highlighted on the left is firing too often... my custom `navigate` event is firing, which restores the scroll position by scrolling you down past the top nav.

Don't spend too much time on it, that was my bad, I can fix if needed!
