### ISSUE TITLE
Add to Cli docs an explanation of generator for  Magic.Link auth provider 

### ISSUE THREAD

**Issue by gizmoGremlin** [redwoodjs/redwoodjs.com#170]
see issue https://github.com/redwoodjs/redwood/issues/623
and pending pull request https://github.com/redwoodjs/redwood/pull/644

Add the Magic.Link provider option in the CLI Docs. This Doc correlates with the information you should see when you run yarn rw g auth --help

**Comment by jtoar** [comment]
@gizmoGremlin I'll cover this.

**Comment by gizmoGremlin** [comment]
Excellent, thank you.
