### ISSUE TITLE
Add environment variable to disable search indexing in development

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#181]
When people are building the site locally they need to comment out some code in order to skip running the search index (which will fail without an Algolia api key). Let's just set an ENV var that says whether or not to worry about populating the search during build time, set to `false` by default—usually you don't care about the search index during development.

We will be sure to set the flag ON for Netlify deployments.

**Comment by jtoar** [comment]
I think #324 addressed this; let me know if not, but I've been able to develop locally without worrying about search since.
