### ISSUE TITLE
"Open link in new tab" gives a 404

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwoodjs.com#188]
Trying to open any of the top-level nav items in the left navigation bar on redwoodjs.com in a new tab or window gives you a 404 page.

![image](https://user-images.githubusercontent.com/30793/84483226-4ffa5100-ac99-11ea-8c50-7283770e21dd.png)

![image](https://user-images.githubusercontent.com/30793/84483532-bf704080-ac99-11ea-8551-af76af6be171.png)

**Comment by cannikin** [comment]
Hmmm yeah there is no `docs/index.html` page, we rely on Netlify to do a redirect for us from `/docs` to the first real doc on the page. But if you look in `netlify.toml` (starting on line 29) we're only redirecting the root directory, not the `index.html`. Netlify has a setting to show what they call "pretty URLs", which to them just means not showing `index.html` in the address bar. It looks like it doesn't also go the other way (mapping a real request for `/docs/index.html` to just `/docs` and then redirecting).

Should be an easy fix!
