### ISSUE TITLE
Searching in the docs leads to 404 pages

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwoodjs.com#189]
Searching for "seed" and clicking on the first result gives me a 404 page

![image](https://user-images.githubusercontent.com/30793/84506071-0f153300-acbf-11ea-923d-be20df16cf7e.png)

![image](https://user-images.githubusercontent.com/30793/84506093-19cfc800-acbf-11ea-8d76-8d7f2f5624d6.png)

The URL is wrong, the correct URL should be https://redwoodjs.com/docs/cli-commands#db-seed

I guess something isn't updating as it should with Algolia

**Comment by jtoar** [comment]
@Tobbe Ah thanks! This came up before briefly after merging #149, but we fixed that by flushing the index. That's probably worth doing again, but this looks like it might be different?

In #155 we made the CLI commands doc's title different than it's menu title. It looks like the search links are using the doc title instead of the menu title.

**Comment by cannikin** [comment]
This is most likely due to this: https://github.com/redwoodjs/redwoodjs.com/issues/180 I'll work on that this morning!

**Comment by cannikin** [comment]
@jrhorn424 Well my fix for #180 didn't help, although it feels good to get that done!

It's still generating the search URL as "command-line-interface.html" instead of "cli-commands.html" because of this: https://github.com/redwoodjs/redwoodjs.com/blob/master/lib/search.js#L44

**Comment by jtoar** [comment]
@cannikin It looks like we need to do 

```javascript
chapter = option.title
```

but wasn't sure where to do it in the control flow (only glanced at it). The if statement before the call wants chapter and section to be null:
https://github.com/redwoodjs/redwoodjs.com/blob/4452d3c13f79d8b4db8d41282d41765b4a2c583c/lib/search.js#L103-L106

**Comment by cannikin** [comment]
All better!
