### ISSUE TITLE
Add "Destroy" Command + options to CLI Doc

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#197]
https://redwoodjs.com/docs/cli-commands

This is effectively duplicating the CLI command:
- should each option be listed independently (same as generate)
- is there a way to combine this with `generate` commands but not break structure?

Probably needs to be listed in full for consistency. Just lot of things...

```bash
rw destroy <type>

Rollback changes made by the generate command

Commands:
  rw destroy cell <name>         Destroy a cell component
  rw destroy component <name>    Destroy a component
  rw destroy function <name>     Destroy a Function
  rw destroy layout <name>       Destroy a layout component
  rw destroy page <name> [path]  Destroy a page and route component
  rw destroy scaffold <model>    Destroy pages, SDL, and Services files based on
                                 a given DB schema Model
  rw destroy sdl <model>         Destroy a GraphQL schema and service component
                                 based on a given DB schema Model
  rw destroy service <name>      Destroy a service component

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```

**Comment by jtoar** [comment]
@thedavidprice Right now, #198 shows what 1) would look like (listing them independently): https://deploy-preview-198--redwoodjs.netlify.app/docs/cli-commands#destroy-alias-d.

One question is: do we think the `destroy` commands will get any more nuanced? If we don't, then taking the second route of co-locating them with their generator might make the most sense, just saying something like "Can be rolled-back with..."

That, and/or we could just keep the table of all the commands and not have an individual section for each one.

**Comment by thedavidprice** [comment]
@jtoar Thanks for taking the time to do this -- helpful to see. Yeah, I just think it adds a lot of "noise". Which happens with the Generators in general but there's just enough that need more detail it seems helpful.

If I could have made the call, Destroy would **not** have been a command but rather a flag on each Generator, e.g. `yarn rw g sdl --destroy`. So I think that's affecting how I feel about this doc.

## Next Iteration 
1. Keep the Destroy introduction ([link here](https://deploy-preview-198--redwoodjs.netlify.app/docs/cli-commands#destroy-alias-d)) and add an example.
2. Add a section at the end of the [Generator Introduction](https://deploy-preview-198--redwoodjs.netlify.app/docs/cli-commands#generate-alias-g), something like "Undoing a Generator with `Destroy` command and include a simple sentence explanation.
3. For each Generator section, e.g. [Generate Cell](https://deploy-preview-198--redwoodjs.netlify.app/docs/cli-commands#generate-cell), add a section between "Usage" and "Example" with a very simple "Undo and Destroy Generated Cells" with the code `yarn rw destroy cell <name>`

Thoughts?

**Comment by jtoar** [comment]
@thedavidprice That sounds great. Should be fixed today.

**Comment by jtoar** [comment]
This one's been done for a while!
