### ISSUE TITLE
Add Doc about DB (Prisma) Relations, RW Generator Support, and Links to Help

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#211]
**Create a new Doc about "DB: Schema Relations"** — currently there's no singular resource for developers to connect the dots:
- How to do schema.prisma relations (from Prisma Docs): https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations
- What, if any, relations are supported by Redwood Generators? Examples?
- What, if any, workarounds exist to use Relations + RW Generators: https://community.redwoodjs.com/t/prisma-beta-2-and-rwjs-limited-generator-support-for-relations-with-workarounds/361

**Comment by Tobbe** [comment]
I read the prisma docs on relations a few days ago, and that was a "aha" moment for me. I was especially confused about the need for both an "author" and an "authorId" field. I thought that was very redundant. But seeing that they were only part of the schema file and not the actual db tables really cleared that up.

That said, I'm not sure it needs to be in RW's scope to explain that. Maybe that should just be part of the required knowledge to have before getting started with RW (with the RW docs only pointing me to the right resources for learning all about it)

**Comment by thedavidprice** [comment]
Ah, agreed about "not being in Redwood's scope", and that's not what I'm suggesting here. I meant to imply this doc would _reference_ which external docs were necessary to do specific things. Pertaining to your "aha" moment, what could we have done better, earlier in the learning process to get you to that doc... or did you understand from the beginning how to learn about the DB schema models?

It's like when you learn to play a new instrument or a new athletic activity; step one is to understand what things are called and what they do. "This is the fretboard and this is a fret... " We have a high-level diagram right now, which I feel does a good job regarding the "what they do" part, but we don't have the "This code is the Prisma Schema Data Model, and here's the docs. This is the Prisma Client object for CRUD, and here's the docs. This is the Apollo GraphQL thingamajigger, and here's the doc."

**Comment by jtoar** [comment]
Made some progress on this in https://github.com/redwoodjs/redwoodjs.com/pull/557 but could still use some more examples for sure.

**Comment by thedavidprice** [comment]
Since this issue was created, there have been several improvements:
- Prisma's Relation documentation (with examples) is very helpful
- Redwood's Scaffold Generators are now able to work with most 1-m and n-m relations

@jtoar I'm in favor of closing this one out. If you have specific ideas for ways to improve the current doc, I'd suggest opening a new issue and bullet pointing 'em.
