### ISSUE TITLE
First Cell should be Posts

### ISSUE THREAD

**Issue by msell** [redwoodjs/redwoodjs.com#22]
I'm going through the tutorial and when I followed the instructions up to the command `yarn rw g cell BlogPosts` and added the `BlogPostsCell` to `HomePage.js` and I was getting a 400 server error.  To get past this error I changed the references to blogPosts throughout the first Cell to just posts and that seemed to correct the issue.

**Comment by cannikin** [comment]
@msell did you get to the next section where you need to rename part of the `QUERY` and then prop that's sent into `Success`? You rename those from `blogPosts` to `posts` and you should be good to go.

> To get you off and running as quickly as possible the generator assumes you've got a root GraphQL query named the same thing as your cell and gives you the minimum query needed to get something out of the database. In this case it called the query `blogPosts` which is not a valid query name for our existing Posts SDL and Service. We'll have to rename that to just `posts` in both the query name and prop named in `Success`.

**Comment by msell** [comment]
Grrr my apologies.  I must have missed/skipped that.  Appreciate the help.
