### ISSUE TITLE
Improve auth doc: more about GoTrue

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwoodjs.com#220]
There's been quite a few questions about Go True lately, and we really don't talk about it that much in the docs (in fact, all we do is link to the GoTrue repo). So it's probably worth expanding on.

For reference on how to set it up, @Terris provided an example app: https://community.redwoodjs.com/t/netlify-gotrue-auth-example/762 (thanks Terris).

---

**Update** @Terris updated the auth readme with the critical getting-started steps in https://github.com/redwoodjs/redwood/pull/765. I'm starting to think a cookbook might be the most appropriate thing to add next.

**Comment by Terris** [comment]
@jtoar - I'd really like to take a stab at writing a recipe for this. I'll work up a draft and maybe you can help me make it cohesive and humane? :)

**Comment by jtoar** [comment]
@Terris Absolutely :+1: sounds like a plan. Thanks for taking this on.
