### ISSUE TITLE
Update Forms doc

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwoodjs.com#239]
We just merged https://github.com/redwoodjs/redwood/pull/749/, so now Forms work as expected. But we should still add a few notes about the coercion:

- [x] Make it more explicit that Redwood handles type coercion on the users' behalf (expected behavior)
- [x] Certain field types (`NumberField`) coerce automatically, but if users needs to set it manually/override it, they can set `dataType` to one of the following: `Boolean`, `Float`, `Int`, `Json`
- [ ] Roadmap: at some point we need to let users optionally pass a function for `dataType` so they can do the conversion however they want

**Comment by thedavidprice** [comment]
Should include something about this PR "support passing coercion functions to form fields" https://github.com/redwoodjs/redwood/pull/973

**Comment by thedavidprice** [comment]
@forresthayes Based on your PR [support passing coercion functions to form fields](https://github.com/redwoodjs/redwood/pull/973), we need to update the Forms doc with how-to info for this capability. Could you reply with a comment here including a brief explanation and possibly an example use?

**Comment by forresthayes** [comment]
My PR changes the `dataType` prop name to `transformValue`.

The original behavior is still supported, but now you can also pass a function to coerce or transform the input however you want.

For example, you might enable a user to enter a long number separated into groups with commas:

```jsx
const coercionFn = str => parseInt(str.replace(/,/g, ''), 10)

<TextField name='threeCommaClub' transformValue={coercionFn} /> //  '1,000,000,000' => 1000000000
```

**Comment by thedavidprice** [comment]
@forresthayes thanks! That's exactly what we need.

@jtoar I moved this to "in progress" on board as a reminder for us to possibly discuss tomorrow.
