### ISSUE TITLE
Wrong cli docs link in search results (404 page)

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwoodjs.com#243]
Searching for `yarn rw dev api` and clicking the first result leads to a 404 page. See screenshots below

![image](https://user-images.githubusercontent.com/30793/87139806-cc844d80-c2a0-11ea-97f4-0b7b218dfd4e.png)

![image](https://user-images.githubusercontent.com/30793/87139679-a78fda80-c2a0-11ea-8f12-1da051ad8a5f.png)

I thought we fixed this already in https://github.com/redwoodjs/redwoodjs.com/issues/189 but it seems to be back :(

**Comment by cannikin** [comment]
So weird... I just rebuilt the index to clear that out. I'm going to check it throughout the day and watch every deploy to see if any of them write to `docs` when they should be writing to `docs-branch`.

**Comment by thedavidprice** [comment]
This is working correctly as of quick tests today.

🎉
