### ISSUE TITLE
Example code in GoTrue Auth Cookbook results in Unhandled Promise Rejection

### ISSUE THREAD

**Issue by mfosker** [redwoodjs/redwoodjs.com#250]
In the example code for the GoTrue Auth Cookbook (https://redwoodjs.com/cookbook/go-true-auth), the line:
```javascript 
{error && <p>{error}</p>}
```
which is used to display any error message, is within the Form component.

This results in an Unhandled Promise Rejection when the signup returns an error.
<img width="551" alt="Screenshot 2020-07-17 at 09 18 54" src="https://user-images.githubusercontent.com/1719698/87764748-c5b08a00-c80e-11ea-9936-66d985cbf8f5.png">

Moving that line ahead of the Form component avoids this issue.
I could do a PR to update the docs to show that line ahead of the Form component but was not sure if this points at a larger issue where it should be OK to have other elements within the Form.

**Comment by cannikin** [comment]
@Terris Any thoughts on this? It's possible this is a global problem with the FormContext somehow, but this cookbook article just happened to expose it.

**Comment by Terris** [comment]
Yes, this was a result of the bug introduced with automatic coercion in 0.13.0 and has since been fixed in 0.14.0.

@mfosker Can you please try to [upgrade your Redwood project](https://redwoodjs.com/docs/cli-commands#upgrade) to 0.14.0 and see if the error is fixed?

**Comment by mfosker** [comment]
Thanks @Terris 
After updating to 0.14.0 I can not longer reproduce that issue.

**Comment by Terris** [comment]
@mfosker Glad to hear! Sorry about the trouble there.

**Comment by mfosker** [comment]
Awesome, thanks!
