### ISSUE TITLE
https://redwoodjs.com/community not found

### ISSUE THREAD

**Issue by benmccann** [redwoodjs/redwoodjs.com#257]
There's a link in the footer to https://redwoodjs.com/community. Clicking it leads to a page that says:
>Page Not Found
Go Home

**Comment by peterp** [comment]
Oooh, whoops, could you open a PR and change that to https://community.redwoodjs.com/?

**Comment by benmccann** [comment]
I'm not quite sure which file to change. It didn't come up on GitHub's search of this repo

**Comment by Tobbe** [comment]
@benmccann If you want to do it, I think it's here https://github.com/redwoodjs/redwoodjs.com/blob/main/code/html/_nav.html#L116

If not, I can do it, let me know :)
