### ISSUE TITLE
Remove BINARY_TARGET ENV var setup

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#269]
After some testing with data migrations it seems like we do NOT need to set `binaryTargets` in `schema.prisma` to `rhel-openssl-1.0.x` any longer. Just leaving it as `native` (which is the default out of the box) is now working during a Netlify deploy.

This means we can remove this section in the tutorial:

![image](https://user-images.githubusercontent.com/300/89068415-025ba580-d326-11ea-961f-873410e1ebbc.png)

**Comment by dthyresson** [comment]
Also, in the Tutorial.md: 

`binaryTargets = env("BINARY_TARGET")` => `binaryTargets = "native"` as this is what v0.15.3 installs.

```
First let's define the data structure for a post in the database. Open up api/prisma/schema.prisma and add the definition of our Post table (remove any "sample" models that are present in the file). Once you're done the entire schema file should look like:


// api/prisma/schema.prisma

datasource DS {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = env("BINARY_TARGET")
}

model Post {
  id        Int      @id @default(autoincrement())
  title     String
  body      String
  createdAt DateTime @default(now())
}
```
