### ISSUE TITLE
Add Troubleshooting doc

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#27]
Can refere to it from the main tutorial, but seems best as a separate doc that will likely be more dynamic.

Can refere to known issues/bugs with links. And/or also include setup and config issues for other systems and preferences.

Here’s one from the forum to include:
>Maybe a short guide on installing database,
>You also have make sure that you have SQLite database installed.
>For installing sqlite on,
>windows choco install sqlite
>ubuntu sudo apt-get install sqlite3
>mac brew install sqlite

**Comment by guledali** [comment]
We should also make a **note** on installing postgresql

**Comment by guledali** [comment]
@thedavidprice 

> Redwood recommends installing the databases for windows user through windows subsystem for linux. The only requirement is that you have **Windows 10 version 16215.0 or higher**

> Go ahead installing the following https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:regionofsystemrequirementstab

> We at Redwood also recommend installing the **new terminal** with it for nicer experience, remember to thank us later. https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab

> Now that everything is installed and the computer is rebooted run these following command

> Installing SQLite you will need it shortly after

```
sudo apt-get install sqlite3
```

> Also for the later stages of the tutorial

```
sudo apt install postgresql
```

> and remember to start it

```
service postgresql start
```

**Comment by thedavidprice** [comment]
Created a "Troubleshooting & How To" category in the forum:
https://community.redwoodjs.com/c/troubleshooting/8

Added the SQLite instructions here:
https://community.redwoodjs.com/t/installing-sqlite-locally/112

@guledali Feel free to add the "Windows postgresql How To" guide if you’d like. I’m sure it will help some people but definitely isn’t necessary. And the main changes I’d suggest to the copy above are:
- write the guide from your own voice as the author, no need to include “Redwood recommends”, etc. Good enough to say "this is what works great for me and you might like it, too!"
- for the terminal part, if you include it maybe make it more clear that it’s optional. It will be better to have _many_ guides that cover very specific topics versus inclusive, lengthy guides with many topics all-in-one. Think of it like SEO for troubleshooting… think of the term people will search for when they have problems or questions, put that term in the title, and write the article with a lazer focus on that topic. Make sense?

Most of all, thanks again for being an active collaborator!
