### ISSUE TITLE
Redirect not working as expected for Tutorial - Part 4

### ISSUE THREAD

**Issue by alvincrespo** [redwoodjs/redwoodjs.com#288]
I was running through part 4 of the tutorial, adding authentication, and ran into an issue where redirecting from /posts didn't actually render anything on the home route. I needed to reload the page.

**Recording**

![redwood-auth-redirect](https://user-images.githubusercontent.com/151311/89897167-9cd0aa00-dbac-11ea-8f96-23c892f9f8c5.gif)

**Environment**

```
➜  redwoodblog git:(master) ✗ node -v
v12.13.0
➜  redwoodblog git:(master) ✗ yarn -v
1.22.4
```

**package.json (web)**

```json
{
  "name": "web",
  "version": "0.0.0",
  "private": true,
  "browserslist": [
    "defaults"
  ],
  "dependencies": {
    "@redwoodjs/auth": "^0.15.3",
    "@redwoodjs/router": "^0.15.3",
    "@redwoodjs/web": "^0.15.3",
    "netlify-identity-widget": "^1.9.1",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }
}

```

**routes**

```javascript
// web/src/Routes.js
import { Router, Route, Private } from '@redwoodjs/router'

const Routes = () => {
  return (
    <Router>
      <Route path="/contact" page={ContactPage} name="contact" />
      <Route path="/about" page={AboutPage} name="about" />
      <Route path="/" page={HomePage} name="home" />
      <Route path="/blog-post/{id:Int}" page={BlogPostPage} name="blogPost" />
      <Private unauthenticated="home">
        <Route path="/posts/new" page={NewPostPage} name="newPost" />
        <Route
          path="/posts/{id:Int}/edit"
          page={EditPostPage}
          name="editPost"
        />
        <Route path="/posts/{id:Int}" page={PostPage} name="post" />
        <Route path="/posts" page={PostsPage} name="posts" />
      </Private>
      <Route notfound page={NotFoundPage} />
    </Router>
  )
}

export default Routes
```

**Comment by thedavidprice** [comment]
Thanks again @alvincrespo

I haven't seen this before and definitely curious about what's getting stuck. And also I haven't noticed the URL query `?redirectTo=/posts` before -- seems like something changed recently.

@jtoar have you seen something like this before? I know there was a Forum topic asking about this, but I believe it was someone trying to manually set logic for `unauthorized` and then call `redirectTo` as needed.

**Comment by peterp** [comment]
We added the `redirectTo` part over here: https://github.com/redwoodjs/redwood/pull/876, I can't imagine why this would be causing this error. I'll start looking into this.

**Comment by peterp** [comment]
I've reverted the `redirectTo` change and I'm still seeing the problem - I'll keep investigating.

**Comment by peterp** [comment]
Reverting this PR resolves the issue: https://github.com/redwoodjs/redwood/pull/836/files
