### ISSUE TITLE
Add Cookbook section

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#3]
Topic list

* Integrating with an outside API
* Creating a custom function
* Creating a RESTful endpoint

**Comment by jrhorn424** [comment]
For integrating with an outside API, were you thinking a standard REST example, like a Star Wars or Movie database? Or something like "when you post a blog post, it triggers a vendor API to send a copy of the post to registered subscribers".

**Comment by cannikin** [comment]
Probably both! We're thinking that it contains lots of common usage pattern examples that we don't cover in the tutorial or the docs. Uploading an image to something like filestack.com, sending an email via sendgrid.com, getting the weather from openweathermap.org... tons of helpful code snippets and writeups, just like a page or two each. We've got someone who got neo4j working as a replacement for Prisma, that'd make for an awesome entry.

My first thought was to make them individual markdown files so each one is self-contained and it's really easy to contribute new ones. Then the build script just packages them all up and lists them in the left nav. We may want to think about a single level directory structure once we get past a dozen or so to keep organized.

**Comment by jrhorn424** [comment]
I agree with the your initial approach. If I understand, no changes to the build script would be necessary? It might be self-evident; I haven't looked. :blush:
