### ISSUE TITLE
Enhance Documentation of Environment Variables

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwoodjs.com#309]
Some thoughts of how we can improve the Environment Variables doc following the merge of #229:

- [ ] Should we consider adding documentation for the providers we're tightly integrated with? We should probably at least link to appropriate sections.
- [ ] Document @dthyresson's awesome netlify env vars plugin.
- [ ] The examples could always be less contrived, especially the `seed.js` example.

I'll add more ideas to this list as they come to me.

**Comment by peterp** [comment]
Another thing to consider is that if it's difficult to explain how our env vars work then we should consider simplifying the implementation.

**Comment by thedavidprice** [comment]
@peterp This would be good to explore further. We have:
- multiple possible env files (.env, .env.defaults, .env.examples)
- that live in different places (.env.defaults in version control but .env ignored)
- with different config requirements per Side
- that need to be managed across a lifecycle (from local dev to production deploy)

Lots of possible trip-ups along the way.

**Comment by peterp** [comment]
I'm looking over the docs and they're really great, but the section called `Where Does Redwood Load My Environment Variables?` is a bit of an implementation detail and I not super relevant to users IMHO.

We could remove this from the `.env.defaults` file:
https://github.com/redwoodjs/create-redwood-app/blob/2d8a54e8e56106485cf60c3b1cee058f76a5c32e/.env.defaults#L9-L10
And set it programatically in the `db` commands instead.

The seeding stuff seems a bit strange, I think we should recommend that a user only creates a single `.env` file, does it require a separate `.env` file?

**Comment by jtoar** [comment]
@peterp Got a new PR over here (https://github.com/redwoodjs/redwoodjs.com/pull/329) with the first change (removing `Where Does Redwood Load My Environment Variables?`). I don't have an opinion on the seeding stuff. Over on issue 797, on the redwoodjs/redwood repo (https://github.com/redwoodjs/redwood/issues/797), we kind of talked about this and both gave thumbs up to having a separate `.env`. But thumbs ups can of course be taken back
