### ISSUE TITLE
Cookbook - Using Supabase for a Username/Password Auth solution

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwoodjs.com#346]
Release v17 added Supabase support and v18 will include signup as well.

A cookbook would explain how to:

* setup Supabase
* use their Postgres database with Prisma
* Use Supabase auth client
* Login and Signup using their auth service
* Use their api client to fetch/manage users

Note: Using Supabase auth *does not* create a User table. One would still need to have a "UserProfile" or "UserRole" table and relation to implement RBAC and have custom user properties.

**Comment by ehowey** [comment]
Just wanted to chime in and say I would love to see this! I am using @Tobbe SupaSlack project as a starting point and muddling my way through a Redwood/Supabase auth integration. I will post a link to what I get done, probably not good enough for a cookbook but maybe gives someone a headstart to create one.

**Comment by ehowey** [comment]
This is where I got to tonight.  Really basic. All it does is allow a sign up, login, and logout. I am going to keep puttering away at it as a learning project and see where I can get it to.  I am going to intentionally leave this as just bare html without styles as the focus is really on the backend integration. 

The goal is to have the following:

- [x] Sign up
- [x] Login
- [x] Logout
- [x] Gated profile page
- [ ] Sign up form with additional fields, e.g. address, that is then shown on profile page.
- [ ] Password reset handling
- [ ] OAuth/Social Login
- [ ] Gated "app" page, based on "user" role
- [ ] Gated "admin" page, based on "admin" role
- [ ] Example integration with Redwood form validation

There is probably more but that is what is on my mind for now.

https://github.com/ehowey/redwood-supabase-auth

**Comment by dthyresson** [comment]
This cookbook helps document this task for user/pwd Supabase authentication: https://redwoodjs.com/docs/how-to/supabase-auth
