### ISSUE TITLE
Cookbook: Turn off the API build process - Should `netlify-plugin-prisma-provider` be removed?

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwoodjs.com#362]
In https://redwoodjs.com/cookbook/disable-api-database

> Turn off the API build process

>When it comes time to deploy, we need to let Netlify know that it shouldn't bother trying to look for any code to turn into AWS Lambda functions.

>Open up netlify.toml. We're going to comment out one line:

```js
[build]
  command = "yarn rw build"
  publish = "web/dist"

  # functions = "api/dist/functions"

[dev]
  command = "yarn rw dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = 'netlify-plugin-prisma-provider'
  [plugins.inputs]
  path = 'api/prisma/schema.prisma'
```

Since just above, have removed the API

```js
rm -rf api
```

Might you now also want to remove the `plugin`?

```
[[plugins]]
package = 'netlify-plugin-prisma-provider'
  [plugins.inputs]
  path = 'api/prisma/schema.prisma'
```

As well?

**Comment by peterp** [comment]
I guess this is important if Netlify complains that it cannot find any functions? 

Otherwise using `yarn rw build web` should be ok.

**Comment by cannikin** [comment]
Done! https://github.com/redwoodjs/redwoodjs.com/commit/59ba9016b805a46f0e25176ed32397ab11923a42
