### ISSUE TITLE
Search results for "typescript" display but fail to load (404)

### ISSUE THREAD

**Issue by forresthayes** [redwoodjs/redwoodjs.com#374]
The redwoodjs.com search results for `typescript` point to urls like `https://redwoodjs.com/docs/typescript.html#web` while the typescript docs are actually located at `type-script` with a dash: `https://redwoodjs.com/docs/type-script.html#web`

This issue was originally patched for the main doc page with a redirect for `https://redwoodjs.com/docs/typescript`, but a PR I proposed might resolve this search bug as well, #337

**Comment by forresthayes** [comment]
@cannikin In case you won't be notified from a closed PR conversation, I replied at https://github.com/redwoodjs/redwoodjs.com/pull/337#issuecomment-702281863

Sorry for the mix up

**Comment by thedavidprice** [comment]
> I think the url for that page should be redwoodjs.com/docs/mocking-graphql-requests, but, given the default conversion from camel case, the actual, current address is https://redwoodjs.com/docs/mocking-graph-ql-requests

@forresthayes This explanation is really helpful. Makes a lot of sense and is a clear problem. 

I 100% think we should apply this fix in a new PR:
https://github.com/redwoodjs/redwoodjs.com/pull/337/files

- [ ] TO-DO: each of these existing pages will need a redirect from current (below) to new slug
- https://redwoodjs.com/docs/type-script (note: already existing redirect that will need to be changed)
- https://redwoodjs.com/docs/mocking-graph-ql-requests
- https://redwoodjs.com/cookbook/mocking-graph-ql-in-storybook
- https://redwoodjs.com/cookbook/go-true-auth
