### ISSUE TITLE
Docs: Add the "deploy" command to CLI Docs

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#380]
Need to add to documentation:

```bash
$ yarn rw deploy --help

rw deploy <command>

Deploy your Redwood project.

Commands:
  rw deploy api <provider>  Deploy the API using the selected provider

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Also see the Redwood CLI Reference
(​https://redwoodjs.com/reference/command-line-interface#deploy​)
```

**Comment by galanggg** [comment]
Hello, how i can help with this one ?

**Comment by forresthayes** [comment]
@galanggg 

Hi! My [pull request](#383 ) is already under review for this issue.

There are a lot of other great first issues available if you're interested in tackling some of those!

**Comment by thedavidprice** [comment]
Hi @galanggg thanks so much for offering to help! It would be great to have you as a contributor.

If you haven't seen it yet, this Issue has a lot of suggestions to help with getting started: https://github.com/redwoodjs/redwoodjs.com/issues/393

And don't hesitate to ask if there's anything we can do to get you going.

**Comment by galanggg** [comment]
> @galanggg
> 
> Hi! My [pull request](https://github.com/redwoodjs/redwoodjs.com/pull/383) is already under review for this issue.
> 
> There are a lot of other great first issues available if you're interested in tackling some of those!

thanks for the information! @forresthayes

**Comment by galanggg** [comment]
> Hi @galanggg thanks so much for offering to help! It would be great to have you as a contributor.
> 
> If you haven't seen it yet, this Issue has a lot of suggestions to help with getting started: #393
> 
> And don't hesitate to ask if there's anything we can do to get you going.



> Hi @galanggg thanks so much for offering to help! It would be great to have you as a contributor.
> 
> If you haven't seen it yet, this Issue has a lot of suggestions to help with getting started: #393
> 
> And don't hesitate to ask if there's anything we can do to get you going.

Hello, I'm also happy if I can help here. and, I'm still looking at the current issues @thedavidprice

**Comment by galanggg** [comment]
> Hi @galanggg thanks so much for offering to help! It would be great to have you as a contributor.
> 
> If you haven't seen it yet, this Issue has a lot of suggestions to help with getting started: #393
> 
> And don't hesitate to ask if there's anything we can do to get you going.

Hello, I'm also happy if I can help here. and, I'm still looking at the current issues @thedavidprice
