### ISSUE TITLE
Using formMethods causes client side validation to stop work

### ISSUE THREAD

**Issue by danvalencia** [redwoodjs/redwoodjs.com#39]
Configuring RedwoodJS `Form` with `formMethods` attribute causes the client side form validation to stop working. I used the `useForm()` method from `react-hook-form` as described in the _Saving Data_ section of the tutorial. 

I tried hard reset of the server, but same result.

I'm using node v12.16.1, yarn 1.19.2.

See attached GIF:
![oOz1iNQOdT](https://user-images.githubusercontent.com/198096/76711545-5430c580-66ce-11ea-9c39-bab755bdebaf.gif)
.

**Comment by cannikin** [comment]
Since you're calling `useForm()` yourself you need to manually pass the option:

    const formMethods = useForm({ mode: 'onBlur' })

Normally we pass everything in the `validation` prop on `<Form>` to the internal `useForm()` call on your behalf, but since you've called it yourself we can't and you need to do it yourself!

**Comment by cannikin** [comment]
I'll add a note about that in the tutorial to make others aware.

**Comment by danvalencia** [comment]
@cannikin it works, thanks!

**Comment by cannikin** [comment]
I added a callout at the end of that section in the tutorial to let people know!
