### ISSUE TITLE
[Docs v0.20.0] Add Setup Command, Deprecate Util Command

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#390]
See https://github.com/redwoodjs/redwood/pull/1234

- Adds new Setup Command
    - moves Tailwind setup to `setup tailwind`
    - adds i18n setup `setup i18n`
- `rw g util tailwind` works but is now deprecated.
    - add warning: deprecated
    - add link to Setup command section

**Comment by lumenCodes** [comment]
Hi @thedavidprice I am interested in this issue.

I am a beginner and I would like to know if this is same as https://github.com/redwoodjs/redwood/pull/1234

Is it just to change the files

**Comment by thedavidprice** [comment]
Hi @lumenCodes Welcome to the Redwood Community! If you haven't read it yet, please make sure you take a look at https://github.com/redwoodjs/redwoodjs.com/issues/393

---

This is a great issue to start with. Our CLI commands were updated via this PR merged in what we call our Framework Repo: redwoodjs/redwood#1234

Due to this code change, we want to make the changes I mention above to this document [CLI-Commands](https://redwoodjs.com/docs/cli-commands). Specifically:
- Indicate this is deprecated (with a link to Setup): https://redwoodjs.com/docs/cli-commands#util
- Add a new Setup command section after [Redwood-Tools](https://redwoodjs.com/docs/cli-commands#redwood-tools-alias-rwt)

One last thing — please create this PR now, but we don't want to _merge_ it until we release version v0.20.0 because that's when the change will take effect. It should happen in about a week. But I'll make sure you get Hacktoberfest credit either way.

Does all that sound good?

**Comment by lumenCodes** [comment]
Yes it does. Thank you.
I will reach out if I have any problem concerning this....
