### ISSUE TITLE
Add call to action to star our repo on the Sticker thank you page

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#432]

**Comment by lumenCodes** [comment]
Hi @cannikin please is there a way for me to get the link to the thank you page?

**Comment by dthyresson** [comment]
@lumenCodes If you grab the repo and look at the file that requests stickers:

https://github.com/redwoodjs/redwoodjs.com/blob/eb137ae18812c8a7e1a582f431c9528b08a42107/code/html/stickers.html#L8

You'll see the form is a [Netlify form](https://docs.netlify.com/forms/setup/#html-forms) that on `submit` will [direct to the success page](https://docs.netlify.com/forms/setup/#success-messages) which is `action="/stickers-thanks.html"`.

You'll add the call to action here:

https://github.com/redwoodjs/redwoodjs.com/blob/main/code/html/stickers-thanks.html

Have you thought about what the CTA would say and what it might look like?

There are some very nice CTA template on Tailwind UI:

https://tailwindui.com/components/marketing/sections/cta-sections

or in @RobertBroersma 's https://statik.ly/categories/heroes (not exactly CTA, but close).

**Comment by RobertBroersma** [comment]
@dthyresson There's a few more CTA-type thingies in https://statik.ly/categories/content 😉

**Comment by cannikin** [comment]
Thanks for the assist @dthyresson!

And thanks for taking this issue @lumenCodes! It would be nice if you could star a repo right from that thank you page but it doesn't appear that GitHub lets you do that—all you can do is link over to the repo and hope the person clicks the Star button.

**Comment by lumenCodes** [comment]
Ok, thanks for the information.

**Comment by lumenCodes** [comment]
Hi, @dthyresson I am really sorry that I can't continue with this issue because my schedule changed and I wouldn't want to hold on to it for a long time.
