### ISSUE TITLE
Tutorial - Database Section missing additional binaryTarget needed for v0.20 and Prisma v2.9

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwoodjs.com#446]
From:

https://community.redwoodjs.com/t/redwoodjs-tutorial-netlify-deployment-unfound-prisma-engine-binary/1414

> I was able to get the app to function normally by adding "rhel-openssl-1.0.x" to the binaryTargets listed in api/prisma/schema.prisma. Below is what my generator client object looks like:

> // api/prisma/schema.prisma

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

> We may want to update the tutorial docs to include this.

---

As part of v0.20 and Prisma 2.9, these Manual Code Modifications are needed for existing apps and thus apply to the instructions for the tutorial as well:

> Prisma v2.9 requires an additional binaryTarget for production deploys to build correctly:
> add the additional binaryTarget "rhel-openssl-1.0.x" to api/prisma/schema.prisma
> see this [example 9](https://github.com/redwoodjs/create-redwood-app/pull/109/files)

The section in TUTORIAL.md here:

https://github.com/redwoodjs/redwoodjs.com/blob/main/TUTORIAL.md#the-database

Could have this configuration info set.

**Comment by mkhbragg** [comment]
PR: https://github.com/redwoodjs/redwoodjs.com/pull/448

**Comment by cannikin** [comment]
Prisma is fixing this in 2.11.0: https://github.com/prisma/prisma/issues/4011

**Comment by cannikin** [comment]
Thanks for the fix @mkhbragg !

**Comment by cannikin** [comment]
Also: 🚀
