### ISSUE TITLE
Highlight the Redwood Jammie award

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#459]
Should go in News for sure.

Maybe even on the home page?

- Awards: https://youtu.be/4xAF3r29GhQ
- Jamsnack: https://youtu.be/EWQJuXlvoiQ
    - re-post videos?

**Comment by jtoar** [comment]
@thedavidprice it's in the news section now. Still want to add it to home?

**Comment by thedavidprice** [comment]
Let's close this one. 

I do think there should be a "credibility" section on the home page that includes things like this award, testimonials, and anything else that helps answer the question "why Redwood?". Not sure what those things might be, however, besides GitHub Stars, NPM Downloads, ... ?
