### ISSUE TITLE
Update Tutorial to reflect changes from `api/prisma` to `api/db`

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#472]
As of `v0.21.0`, new projects now use `api/db`. Starting with the https://redwoodjs.com/tutorial/redwood-file-structure section of the Tutorial, we need to update references, images, and code to reflect this change.

**Comment by cannikin** [comment]
Looks like someone fixed this already?

![image](https://user-images.githubusercontent.com/300/100645973-479edc80-32f2-11eb-8b24-539890822448.png)

**Comment by Tobbe** [comment]
> Looks like someone fixed this already?

https://github.com/redwoodjs/redwoodjs.com/pull/473

**Comment by AsdethPrime** [comment]
I am creating pull requests to fix them as I find them :) that way I feel like I am contributing :)
