### ISSUE TITLE
Document new --tests and --stories flags for our generators

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwoodjs.com#486]
See https://github.com/redwoodjs/redwood/pull/1454 for context

**Comment by thedavidprice** [comment]
@96RadhikaJadhav this is also a good first issue, it's just not explained well enough.

- The document (and specific section) that needs updating is here: https://redwoodjs.com/docs/cli-commands#generate-alias-g
- Per PR redwoodjs/redwood#1454 there are 5 Generator commands that needs updating:  Cell, Component, layout, page, service
- For each of these commands, there are two new options (aka flagst) that default to `true`: `tests = true, stories = true`

Would you like me to assign this to you?
