### ISSUE TITLE
Update directory structure description/screenshot for api/confg/dbInstance.js

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#50]
Assuming this is merged: https://github.com/redwoodjs/create-redwood-app/pull/40

**Comment by jrhorn424** [comment]
I can help with this. I don't know if I can explain the reason for this change, or if describing that is even in the scope of this change.

**Comment by cannikin** [comment]
This is pretty much just a duplicate of #65, closing!
