### ISSUE TITLE
findOne() -> findUnique()

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#505]
As of 2.12.0 Prisma is deprecating `findOne()` in favor of `findUnique()`. We've got a couple instances of `findOne()` in several docs.

**Comment by 96RadhikaJadhav** [comment]
@cannikin  Can I work on the issue?

**Comment by thedavidprice** [comment]
@96RadhikaJadhav please do! Thank you for offering. I'm assigning to you now.

- do reach out to @cannikin directly for help and PR review, although others might step in as well
- do **not** change the Tutorial — that will first need code changes and then copy updates
- do look through everything in [Docs/](https://github.com/redwoodjs/redwoodjs.com/tree/main/docs)

🚀

**Comment by thedavidprice** [comment]
Ah, sorry @96RadhikaJadhav I was moving quickly and didn't see #506 is already in progress. 😞 

Please feel free to jump on any docs related issues as they come! We're pretty loose with assignments as docs change/move quickly.

I saw another Issue that is also a good first issue. Will `@` you from #486

**Comment by cannikin** [comment]
Sorry I missed this request @96RadhikaJadhav, it came in after I went to bed! But like @thedavidprice said, feel free to jump on anything that looks interesting to you, you don't need to wait for us. 🙂
