### ISSUE TITLE
Catch promise rejections in build step and raise error

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#51]
Thanks to:

```10:02:48 AM:   (node:1302) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

If something goes wrong during the build phase Netlify doesn't think anything bad happened and will happily deploy the (broken) site.

**Comment by thedavidprice** [comment]
promises promises

**Comment by cannikin** [comment]
Closed by 15832ece97f49094b05e22bf5eafad0ca277423e
