### ISSUE TITLE
Redwood Tutorial Part 2: RBAC delete hits 404 on refetchQueries

### ISSUE THREAD

**Issue by KrisCoulson** [redwoodjs/redwoodjs.com#523]
In Part 2 of the tutorial in the RBAC sections we are asking followers to delete comments, 
```
const [deleteComment] = useMutation(DELETE, {
    refetchQueries: [
      {
        query: CommentsQuery,
        variables: { postId: comment.postId },
      },
    ],
  })
```
  
  
while this does delete the comment. The refetchQuries will fail. 
It fails because nowhere in the tutorial do we have the follower have `postId` returned in the `CommentsCell` so this variable `comment.postId` is `undefined`

The fix is to mention adding the `postId` to the `CommentsCell`.

```
export const QUERY = gql`
  query CommentsQuery($postId: Int!) {
    comments(postId: $postId) {
      id
      postId
      name
      body
      createdAt
    }
  }
````

Additionally, we will need to update the `CommentsCell.mock.js` with the `postId`

**Comment by thedavidprice** [comment]
Thanks @KrisCoulson --> looping in @cannikin

**Comment by cannikin** [comment]
Good catch, thanks @KrisCoulson

**Comment by cannikin** [comment]
@forresthayes Did you get this far in part 2? Can you confirm getting a 404 here?

**Comment by zainfathoni** [comment]
@cannikin I can confirm that I was getting a 404 in that step.

<img width="523" alt="Screenshot 2021-01-26 at 1 06 50 AM" src="https://user-images.githubusercontent.com/6315466/105739188-ccb11580-5f72-11eb-894d-c3f452d9ed2a.png">

And this is how the terminal looks like:

<img width="380" alt="Screenshot 2021-01-26 at 1 08 03 AM" src="https://user-images.githubusercontent.com/6315466/105739309-f2d6b580-5f72-11eb-913c-dfc5f90fb24d.png">

I have submitted #527 PR to address this issue (and another issue I found within this RBAC section), please review it. 😁 
Thanks! 🙏

**Comment by cannikin** [comment]
Thanks @zainfathoni, that fix looks good (see comment in the PR)!
