### ISSUE TITLE
List of packages in Contributing doc needs updating

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#536]
This doc is out of date and needs some TLC: https://redwoodjs.com/docs/contributing
- need to update the number of contributors (ask me for details)
- list of packages needs updating

**Comment by TawfikYasser** [comment]
Hi @thedavidprice  I want to update the number of contributors.

**Comment by thedavidprice** [comment]
@TawfikYasser thanks for jumping in to help!

You can update it to say "more than 170 contributors".

Also, can you update the list of packages from here?
https://github.com/redwoodjs/redwood/tree/main/packages

**Comment by TawfikYasser** [comment]
Okay, I will do that, Please tell me the appropriate file need to be update for `Number of contributors`

For the list of packages I want to update but I can not understand what is needed? Please explain more.

**Comment by TawfikYasser** [comment]
@thedavidprice  I can’t find the HTML file for docs to update the number of contributors

**Comment by thedavidprice** [comment]
Sure thing! Here's the doc that needs updating:
https://github.com/redwoodjs/redwoodjs.com/blob/main/docs/contributing.md

- update "As of this writing, there are over 100 individuals"
- the only package that's missing from [here](https://github.com/redwoodjs/redwood/tree/main/packages) is the `api-server`. You can add it with a link. And the description can be "Run a Redwood App using an Express server alternative to a serverless API"

Make sense?

**Comment by TawfikYasser** [comment]
Great, Okay

Thanks @thedavidprice I will do that

**Comment by TawfikYasser** [comment]
I think updates are now done. #538
