### ISSUE TITLE
File routes.d.ts (part of the basic RW project is ill-formatted 

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwoodjs.com#539]
While this is just an aesthetical problem I think no imperfections are too small for RW. Also, I am not yet comfortable creating a PR (this file could be generated for example). Whoever gets that fixed - please copy me on the fix 😄 

![image](https://user-images.githubusercontent.com/2712405/106671402-75b3cd80-657c-11eb-8d6e-d767c3b03b2d.png)

**Comment by Tobbe** [comment]
You are correct, this file is generated. *.d.ts files are often generated when you build TypeScript projects.

**Comment by adriatic** [comment]
For my education only: closing this issue without fixing it indicates that there are issues that are too small to be addressed, right?

**Comment by Tobbe** [comment]
@adriatic No, not at all. Sorry if I was unclear. That file you posted a screenshot of is generated, so there is nothing we can do about the formatting.

**Comment by adriatic** [comment]
See, I was hoping that you will fix the code that emits this file, so I will see where and how this generation takes place

**Comment by Tobbe** [comment]
Those files that end with .d.ts are TypeScript Definition files. They are
generated by the TypeScript compiler, tsc. You can read more about those
files here:
https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html

**Comment by adriatic** [comment]
Thanks, @Tobbe - I a well aware of all that, however, was not precise enough in my previous message: my assumption was that it is some RW internal tool that generates these files, perhaps based on some RW-supplied template.

I am a big fan of strongly typed languages, started using Pascal in 1970, right after it was created.

**Comment by Tobbe** [comment]
Thank you @adriatic. I dug in to it more, and you are right. We can fix this. The relevant code is here if you want to take a look https://github.com/redwoodjs/redwood/blob/19bb1b5f39dae7d6863096b560bc3549889a7b9a/packages/core/src/babelPlugins/babel-plugin-redwood-routes-auto-loader.ts#L52-L63

**Comment by adriatic** [comment]
# :smile:  :smile:  :smile:

**Comment by Tobbe** [comment]
Now that I knew about it, it bugged me too. So I wrote a PR for it. We'll see what the rest of the RW teams thinks about it :) 
https://github.com/redwoodjs/redwood/pull/1724

**Comment by adriatic** [comment]
I looked at your changes and thought "how creative" - while it looks like a hack, compensated for the inadequacy of the tooling for this code generation 😄
