### ISSUE TITLE
 Tutorial Part 2 *Link* is not working properly

### ISSUE THREAD

**Issue by TawfikYasser** [redwoodjs/redwoodjs.com#541]
Hi

## I think that **Tutorial Part 2 Link** here: 👇

![Image-1](https://user-images.githubusercontent.com/54971231/106960577-f6252a80-6744-11eb-9fa3-710de4d8c2c4.png)

## Is not working properly, Because it is going to `404 Page` as follows: 👇

![Image-2](https://user-images.githubusercontent.com/54971231/106960663-13f28f80-6745-11eb-84bb-2d68d71922d2.png)

## And it should redirect to the following page link: 👇 

![Image-3](https://user-images.githubusercontent.com/54971231/106960708-24a30580-6745-11eb-9f9a-d2a692011739.png)

## Also these links not working: 👇

![Image-4](https://user-images.githubusercontent.com/54971231/106961662-97f94700-6746-11eb-80b2-793d9bcecb33.png)

If it is true, I will be happy to open a PR and fix it.

Thanks

**Comment by cannikin** [comment]
Yup that's busted! We would love a PR to fix that link, thanks @TawfikYasser !

**Comment by TawfikYasser** [comment]
Thank you very much @cannikin 
Also I have updated the issue now by some links below Tutorial Part 2, They also not working

I will open A PR to fix them

Thanks again. :)

**Comment by cannikin** [comment]
Already mentioned this in the PR, but: these links are meant to link to other parts of the tutorial *when views on redwoodjs.com*. The links will indeed not work when viewed on github. This is the intended behavior.
