### ISSUE TITLE
Update schema-relations doc to talk about pitfalls of many-to-many relationships

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#547]
See: https://github.com/redwoodjs/redwood/pull/1758#issuecomment-776266785

**Comment by thedavidprice** [comment]
Grabbing this one and on my list for v0.25 tasks. Will use copy from comment linked above (super helpful). And, where applicable, I'll make other edits as well were copy is outdated.

Let me know otherwise if you're already working on this.

**Comment by jtoar** [comment]
I think this was closed by https://github.com/redwoodjs/redwoodjs.com/pull/557, so closing for now. Let me know if that's not the case.
