### ISSUE TITLE
Improving the nav links in the CLI Commands doc

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwoodjs.com#579]
Some of the nav links in the [CLI Commands](https://redwoodjs.com/docs/cli-commands) doc clash (most notably #db). Maybe we should make sure all sub-command nav links are prepended with their parent command the way setup is:

https://redwoodjs.com/docs/cli-commands#setup
https://redwoodjs.com/docs/cli-commands#setup-deploy-config
https://redwoodjs.com/docs/cli-commands#setup-auth

So prisma commands would be

https://redwoodjs.com/docs/cli-commands#prisma
https://redwoodjs.com/docs/cli-commands#prisma-db

Instead of just:

https://redwoodjs.com/docs/cli-commands#db

I think I didn't do this at first just to keep things from getting too cluttered on the right, and so you could scan the command hierarchy. Thoughts @cannikin @thedavidprice?

**Comment by thedavidprice** [comment]
If we haven't had problems already, definitely feels like we'll be running into them with the anchor tag namespace. I like you're proposed structure above.

And also agree this naming structure would clutter up the right nav a bit and also some headers. However, when I'm scrolling through a command with many options (or sub-commands), it's can be hard to know what section I'm in. E.g. the destroy commands vs generate. So maybe it's an overall best case to use the full command for all headers. I'm game.

Hesitant to suggest we get fancy with the parsing. Will defer to the judgment of others.

**Comment by cannikin** [comment]
We could update the code that generates the right nav to make sure that every anchor is unique. Right now it just kebab-cases the heading of the section without worrying about what else already exists.

**Comment by jtoar** [comment]
@cannikin I don't think it's an issue we'll run into too often, but definitely something we could think about. I think what would make parsing for it more of an imperative is if it means we'd have to think about redirects? If so then I'd want to make sure it doesn't happen, 'cause those are a hassle.
