### ISSUE TITLE
Cookbook: Explain Supabase Permissions and Policies for Row Level Security

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwoodjs.com#584]
An important feature in Supabase postgres is RLS - row level security.

If RLS policies are not enabled on tables, anon access *may* be possible to row level data, including inserts and deletes.

Since Prisma migrate does not add that policy when creating a table (or even the implicit many-to-many join tables), redwood should document some best practices to adhere to when using Supabase as its postgres database with Prisma.

Explain:

* permissions and grants
* schemas
* RLS and policies
* roles
* creating policies for select, insert, update, delete, etc
* api tokens and how they map to roles
* how Prisma interacts at the "postgres" user level vs how an authentication Supabase client user might interact with data
* how to secure your db and api
* how to combine RW requireAuth (via Prisma) with Supabase auth (if using Supabae client)

This YT video from Supabase is a good start:

https://www.youtube.com/watch?v=0LvCOlELs5U

`How to restrict table access to authenticated users, row level policies, and email domain based access`

**Comment by mr-bjerre** [comment]
I'd love to see this !! Have there been any progress on it?

**Comment by dthyresson** [comment]
I think this is a topic better suited for Supabase documentation and their content here https://supabase.com/docs/guides/auth/row-level-security.

That said, once Prisma lets you set the JWT per transaction -- or Redwood has an example of using the Supabase client instead of Prisma for data fetching/writing then RLS should be mentioned ... but the content is best with their docs.
