### ISSUE TITLE
The code for the `BlogPostsCell.js` is syntactically incorrect

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwoodjs.com#586]
Details:
I am referring to code presented in the [Cells section of the Tutorial I](https://redwoodjs.com/tutorial/cells#our-first-cell), fourth instance of the code listing from the beginning of this section, code which indicates where to replace generator created `blogPosts` with `posts`

![image](https://user-images.githubusercontent.com/2712405/108770447-4a435380-7528-11eb-9d67-18c4b83c48b0.png)

**Comment by cannikin** [comment]
Good catch, thanks! Just pushed a fix. :)

**Comment by adriatic** [comment]
I have a terrific gift to catch **other people's** mistakes (mine, not so)
