### ISSUE TITLE
Confusing description of BlogPostCell.js

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwoodjs.com#603]
**Context**: "Our first Cell" section in the Tutorial document

The first time through. I replaced the whole content of the `web/src/components/BlogPostsCell/BlogPostsCell.js` with the text from that "image". Recovery from that was anything but easy. It made me try to use LogRocket to debug my way out - luckily I recalled that I lost the beginning of this (BlogPostCell.js) file

![image](https://user-images.githubusercontent.com/2712405/109530319-93455b80-7a84-11eb-951c-f3319c026ec4.png)

A similar situation in `web/src/components/BlogPostsCell/BlogPostsCell.js` is handled like

// QUERY, Loading, Empty and Failure definitions...

**Comment by thedavidprice** [comment]
Thanks @adriatic Agreed there's room for improvement here. We used to not have the (subtle) highlighting around code snippets, which has definitely been an improvement. It seems we should indicate there's code before/after (as applicable) the displayed section. 

Do you have any suggestions on how we could generalize this throughout the Tutorial? My shorthand is to use `...`, which is probably too subtle.

**Comment by dthyresson** [comment]
The tutorial does say right above that content that it applies to the `Success` component:

>Now we're in the realm of good ol' React components, so just ***build out the Success component*** to display the blog post in a nicer format:

Maybe simply emphasize that part of the instructions?

**Comment by thedavidprice** [comment]
Remembering when I first went through the Tutorial and everything was new, it did trip me up a few times to not be able to orient the displayed snippets within the files. No line numbers, double-checking if I was in `BlogPostCell` vs `BlogPostsCell`, not fully grokking all the components included in the Cell itself... 

So the emphasis could help, but I think there'd be more value in visual orientation cues within the code snippet itself.

**Comment by adriatic** [comment]
I propose an "enhanced" and consistent use of this:

![image](https://user-images.githubusercontent.com/2712405/109693886-2b604500-7b58-11eb-9dcb-832da42d6748.png)

Enhanced means that it would be better to make such comments (both the file path and the indicator that there is some code missing) less "faded", like this:

![image](https://user-images.githubusercontent.com/2712405/109694264-9c076180-7b58-11eb-8318-8b7d369c2d76.png)

The use of "comment" ( // ) is great as even of someone misses the fact that these comments are meta-data, taking them as well does no harm 😄

**Comment by cannikin** [comment]
Added `// QUERY, Loading, Empty and Failure definitions...` in that block and a couple more.

**Comment by adriatic** [comment]
Very quick reaction, thanks @cannikin
