### ISSUE TITLE
Clarify extending imports in case of Apollo Client and React Hook Forms

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#604]
cc @jtoar 

Continuing discussion from here: https://github.com/redwoodjs/redwood/issues/1893

Our Forms documentation might be fine as is.

For Apollo Client, we don't have any documentation available to provide information or instructions: what is imported, how to import additional items, etc.. There's a cookbook PR here https://github.com/redwoodjs/redwoodjs.com/pull/563, but that wouldn't be the right place.

- should we create a stand-alone GraphQL Doc (for Server and Client)?
- and/or is there anywhere inline we could add information about what's imported and how to import others?

**Comment by jtoar** [comment]
I'll add it here and get this mergeable right now https://github.com/redwoodjs/redwoodjs.com/pull/233; been far too long!
