### ISSUE TITLE
How to handle `migration_lock.toml` when switching from SQLite to Postgresql?

### ISSUE THREAD

**Issue by ajcwebdev** [redwoodjs/redwoodjs.com#612]
Right now the tutorial assumes SQLite up until the [database deployment step](https://redwoodjs.com/tutorial/deployment#the-database). At this point we provide a warning that you have to switch to Postgres and stay with that on your local machine, along with a link to the local postgres setup guide.

>Prisma only supports one database provider at a time, and since we can't use SQLite in production and must switch the Postgres or MySQL, that means we need to use the same database on our local development system after making this change. See our [Local Postgres Setup](https://redwoodjs.com/docs/local-postgres-setup) guide to get you started.

This guide is really fantastic! Unfortunately it would be more useful to know at the beginning so you could just skip the entire headache and work with Postgres in development the entire time. Why do I say this? Lets follow the user journey of these docs. Once you get to the postgres setup page you get [this](https://redwoodjs.com/docs/local-postgres-setup#migrations):

>If you've already created migrations using SQLite, you just need to run migrations again:

```
yarn rw db up
```

If you've been following the last few releases of Redwood you may immediately notice these are the old Prisma commands. This is confirmed when you run `yarn rw db up`:

```
WARNING: deprecated command
Please use the new command: yarn rw prisma migrate dev 

See the Redwood CLI Reference (​https://redwoodjs.com/docs/cli-commands#prisma​) 
```

If you then enter `yarn rw prisma migrate dev` you get the following message:

```
Running Prisma CLI:
yarn prisma migrate dev --preview-feature --schema "/Users/ajcwebdev/projects/migration-lock-uh-oh/api/db/schema.prisma" 

Prisma schema loaded from db/schema.prisma
Datasource "DS": PostgreSQL database "railway", schema "public" at "containers-us-west-1.railway.app:5581"

Error: P3014

The datasource provider `postgresql` specified in your schema does not match the one specified in the migration_lock.toml. You will encounter errors when you try to apply migrations generated for a different provider. Please archive your current migration directory at a different location and start a new migration history with `prisma migrate dev`.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This error makes sense, if we check our `migration_lock.toml` the problem is immediately obvious:

```toml
# Please do not edit this file manually
provider = "sqlite"
```

But if we continue to follow the instructions and enter `prisma migrate dev`:

```
prisma migrate dev
```

And of course we shouldn't expect this command to work because that's not the command in Redwood, it's if you're just using Prisma.

At this point I'm gonna start going off script, so [here's a repo of my exact project state at this point](https://github.com/ajcwebdev/migration-lock-uh-oh/tree/main/api/db). You'll notice I've still got the `migration_lock` file in there because at this point I've been given a series of commands that haven't worked. So the first thing we may think to do is just delete `migration_lock` and try `migrate dev` again.

```
Running Prisma CLI:
yarn prisma migrate dev --preview-feature --schema "/Users/ajcwebdev/projects/migration-lock-uh-oh/api/db/schema.prisma" 

Prisma schema loaded from db/schema.prisma
Datasource "DS": PostgreSQL database "railway", schema "public" at "containers-us-west-1.railway.app:5581"

Error: P3006

Migration `20210306174129_sqlite_migration` failed to apply cleanly to a temporary database. 
Error:
Database error: Error querying the database: db error: ERROR: syntax error at or near "AUTOINCREMENT"
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:192
   1: sql_migration_connector::sql_database_migration_inferrer::validate_migrations
             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:70
   2: migration_core::api::DevDiagnostic
             at migration-engine/core/src/api.rs:100

error Command failed with exit code 1.
```

Hmmmmmm, okay, nuke the whole migrations folder?

```
rm -rf api/db/migrations
```

```
Running Prisma CLI:
yarn prisma migrate dev --preview-feature --schema "/Users/ajcwebdev/projects/migration-lock-uh-oh/api/db/schema.prisma" 

Prisma schema loaded from db/schema.prisma
Datasource "DS": PostgreSQL database "railway", schema "public" at "containers-us-west-1.railway.app:5581"

✔ Name of migration … it-worked
The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20210306181908_it_worked/
    └─ migration.sql

✔ Generated Prisma Client (2.16.1) to ./../node_modules/@prisma/client in 65ms

Everything is now in sync.
```

Okay, so there's a couple things we could potentially take away from this:

1. Change the docs to recommend Postgres from the very beginning?
2. As soon as we get to the "!!! Extremely Important Notice You Should Read !!!" we should also provide the "!!! Extremely Important Nuke My DB Command You Should Read !!!" and resolve the problem right now. Just a note that says:

To reset your database run:

```
rm -rf api/db/migrations
yarn rw prisma migrate dev
```

Sorry for the super long issue, if any Prisma people read this you all are amazing and we appreciate your hard work!

**Comment by cannikin** [comment]
Yeah that Postgres doc needs updating!

We definitely want to keep the tutorial starting with SQLite, it's just too convenient. Asking people to install/setup Postgres before they actually start using Redwood is just too much of a leap, especially for folks that are new to coding and have zero sysadmin experience. They'll leave and never come back. :(

BUT, I'd be all for adding a more in-depth message to the start of the tutorial along the lines of "By the end of this doc we're going to have to switch over to Postgres. If you're comfortable installing and using Postgres, you can start using it now and skip the headache later. Here are the changes to `schema.prisma` ..."

How's that sound?

**Comment by ajcwebdev** [comment]
Here's a good link to [Danny's migration guide](https://community.redwoodjs.com/t/upgrading-to-redwoodjs-v0-25-and-prisma-v2-16-db-upgrades-and-project-code-mods/1811) that provides a lot of useful information here, unfortunately this seems to be an issue that goes beyond just upgrading to Redwood v0.25 since I was on v0.26 when this happened, so this is more about the general workflow we've got going on here.

I would have agreed with you Rob until I used Railway, I think actually getting that setup and just sticking that env var in a .env is ridiculously simple, much simpler than trying to bug these issues we're running into right now. I did this flow for a meetup talk recently that'll I'll make sure to share here once it's out, I think the flow can actually be much better than you think.

Otherwise I agree that just giving them simple, explicit instructions right when you need to switch dbs is good, the problem is we are leading people down this maze of links and error messages right now.

**Comment by Tobbe** [comment]
I think using a remote DB, even for just doing the tutorial and for general playing around with RW makes a lot of sense. It's super easy to get up and running, no need to install anything. And it leaves you in a great spot for transitioning to a production ready app. It's later, when you need the speed and control of running your own local DB, that's when you should worry about installing postgres locally

**Comment by ajcwebdev** [comment]
## [Getting Dynamic with Prisma Migrate, PostgreSQL and Railway](https://redwoodjs.com/tutorial/getting-dynamic)

## Create your first project

![01-](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/qb4q3381cb8w8ek5mrks.png)

### ⌘ + K

![02-](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/jhr9oamt57al7gyew4yc.png)

### Provision PostgreSQL

![03-](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/vqa630ipwswqkbv4uijp.png)

### IT'S ALREADY SO BIG THOUGH

![04-](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/v5bw59yuzh2iyhi7e5cq.png)

### Select PostgreSQL on left sidebar

![05-](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/t4qwo7rrutd8gasfm2sb.png)

### Click Connect

![06-](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/dyiiv58ib7w71jcta1uq.png)

### Copy paste your database URL (this db was deleted)

![07-](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/36nsoelfsifgbfsaqayf.png)

## Set environment variable

```bash
touch .env
```

```
DATABASE_URL=
```

## `schema.prisma`

```prisma
// api/db/schema.prisma

datasource DS {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = "native"
}

model Post {
  id        Int      @id @default(autoincrement())
  title     String
  body      String
  createdAt DateTime @default(now())
}
```

## `redwood prisma migrate`

```
yarn rw prisma migrate dev --name nailed-it
```

```
Running Prisma CLI:
yarn prisma migrate dev --name nailed-it --preview-feature --schema "/Users/ajcwebdev/projects/ajcwebdev-redwood/api/db/schema.prisma" 

Prisma schema loaded from db/schema.prisma
Datasource "DS": PostgreSQL database "railway", schema "public" at "containers-us-west-1.railway.app:5884"

The following migration(s) have been applied:

migrations/
  └─ 20210307113114_nailed_it/
    └─ migration.sql

✔ Generated Prisma Client (2.16.1) to ./../node_modules/@prisma/client in 89ms

Everything is now in sync.
```

## `migrations`

```sql
CREATE TABLE "Post" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
```

## `redwood generate scaffold`

```
yarn rw g scaffold post
```

```
✔ Generating scaffold files...
  ✔ Successfully wrote file `./api/src/graphql/posts.sdl.js`
  ✔ Successfully wrote file `./api/src/services/posts/posts.scenarios.js`
  ✔ Successfully wrote file `./api/src/services/posts/posts.test.js`
  ✔ Successfully wrote file `./api/src/services/posts/posts.js`
  ✔ Successfully wrote file `./web/src/layouts/PostsLayout/PostsLayout.js`
  ✔ Successfully wrote file `./web/src/pages/EditPostPage/EditPostPage.js`
  ✔ Successfully wrote file `./web/src/pages/PostPage/PostPage.js`
  ✔ Successfully wrote file `./web/src/pages/PostsPage/PostsPage.js`
  ✔ Successfully wrote file `./web/src/pages/NewPostPage/NewPostPage.js`
  ✔ Successfully wrote file `./web/src/components/EditPostCell/EditPostCell.js`
  ✔ Successfully wrote file `./web/src/components/Post/Post.js`
  ✔ Successfully wrote file `./web/src/components/PostCell/PostCell.js`
  ✔ Successfully wrote file `./web/src/components/PostForm/PostForm.js`
  ✔ Successfully wrote file `./web/src/components/Posts/Posts.js`
  ✔ Successfully wrote file `./web/src/components/PostsCell/PostsCell.js`
  ✔ Successfully wrote file `./web/src/components/NewPost/NewPost.js`
✔ Adding scaffold routes...
✔ Adding scaffold asset imports...

✨  Done in 2.10s.
```

Open a browser, enter `localhost:8910/posts`, and create a post about how much smarter you are than Rob.

![Alt Text](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/s3phm8b3e5fv4b0k04vm.png)

**Comment by ajcwebdev** [comment]
I also rewrote [Part 3 of A First Look at Redwood to follow this exact flow](https://dev.to/ajcwebdev/a-first-look-at-redwood-js-part-3-5ao5)

**Comment by cannikin** [comment]
hahaha

Okay so even with Railway you have to explain Railway, `schema.prisma` provider, ENV vars, the `.env` file, not checking that file in, internet access required...and if you don't explain it and be like "trust us, just do this," then it becomes the antithesis of everything the tutorial stands for! Oh, and if it takes you longer than 7 days to get through the tutorial, your database disappears!

I'd much rather the user feel the pain at the *end* of the tutorial than right at the beginning. But again, a message at the top that links you over to @ajcwebdev's summary above if you want to start off on Postgres, I'm all for it.

**Comment by ajcwebdev** [comment]
Yeah I'd be curious to get thoughts from other people in the community about this. I think those are all valid concerns, but I don't think getting away from managing environment variables is possible at this point, and introducing them earlier could actually be beneficial.

I agree the `.env` file is the trickiest part. We've had everyone managing them once they're on the Netlify dashboard but that guarantees they won't know what they are when they are deploying. This would at least introduce the concept earlier and `.env` is set to `.gitignore` by default.

Now that I've started doing it this way I find that just going from managing two database to only managing one is a huge win for simplicity. My real concern here though is that anyone who is going to be confused by any of that will still be 100% confused by what is happening right now in the tutorial, going back to why I opened the issue in the first place.

If you're going to get caught in a weird state with your database you have to know how to move forward instead of getting shuffled around to a bunch of 3rd party docs that aren't even connected to the tutorial at all, or a bunch of forum posts that are tangentially related but don't actually answer your specific blocker.

**Comment by mojombo** [comment]
I think it's helpful to think about the tutorial as part of the Redwood onboarding funnel. You start at the RedwoodJS homepage and if you like what you see, you jump into the tutorial to see how it works. At this point, the relationship with the viewer is very fragile. We're one error, one confusing sentence, one why-do-I-have-to-do-this-complicated-thing away from losing them. We need to get people to their first win very, very fast or the tutorial has failed. We need to consistently give those wins, or the tutorial has failed. The tutorial is long enough that we will lose probably 95% or more of all readers before they even get to the "deploy to production" step. If we still have them by then, I'd consider it a massive win.

All this to say, I think the tutorial should be optimized for getting the reader through as much of it as possible. If that's the goal, then any DB setup stuff early on will defeat that goal. Keeping it with SQLite does make the transition to production harder, but we can streamline that as much as possible and if you've made it that far, your tolerance for stuff like that will be much higher than at the beginning of the tutorial. Plus, once you've set up Postgres locally, you can start your REAL Redwood project on Postgres and not have the pain again.

@ajcwebdev I think during demos, where you know what you're doing, you should do the Postgres-from-the-beginning approach to make it smoother, and that's awesome. Definitely demo it that way! Live demos and the tutorial are different contexts, though, and can warrant different approaches.

**Comment by cannikin** [comment]
We want to get people into using *actual* Redwood with as little mental overhead as possible. If you're a seasoned dev sure, ENV and `.env` and a remote database is nothing to you, and doesn't add any mental friction to getting started. But for someone relatively new it's just more clutter in their head *that we can avoid completely*...that's tough to pass up. They'll still have to pay the piper at some point, but once you get to deployment you've accepted that you're going to have more work to do, just by the very nature of going to production. And as your original post shows, updating your local database once you've switched to Postgres is two commands.

Your original post is correct: the current process is confusing as hell. But only because those Postgres docs are out of date! So I think this issue is for fixing that doc (and it can even include your Railway setup steps/images above).

**Comment by ajcwebdev** [comment]
Yeah, I'd recommend at least doing a run through of it and verifying that it still makes sense. I've deployed versions of the tutorial app close to a dozen times by now and it threw me off, for sure, and I believe it threw @pi0neerpat and @agiannelli off as well.

And no worries about the Railway setup, I'm doing a full refactor of the First Look series right now so that's why I'm iterating on a lot of different tech and workflows for doing this. I'm probably going to end up with slightly different stack and a very different sequence of topics that the official tutorial.

Hopefully people will do whichever makes more sense to them, but I HIGHLY recommend people do the official docs first, and I don't want to steer them in the wrong direction with that advice.

**Comment by ajcwebdev** [comment]
Thanks for the response @mojombo. This is a tricky one since we've really promoted the tutorial we want to make sure it's going to work in as many cases for as many people as possible and I appreciate you all weighing in here. I agree with the trade offs being between getting people as far into the tutorial as they can while still having the full end to end experience.

Something to think about also could be writing a db provider specific setup command that just handled the keys for you, so you could imagine signing up for something like Railway, and then you enter a `rw` command that prompts you for your URL and you just copy paste it and then it puts it where it needs to go.

I wonder  with the kind of dashboards some of these db providers are building if we'll get to a point where that'll be an even simpler workflow than running SQLite locally. Especially when you look at the kind of visual introspective tools they're giving you.

>@ajcwebdev I think during demos, where you know what you're doing, you should do the Postgres-from-the-beginning approach to make it smoother, and that's awesome. Definitely demo it that way! Live demos and the tutorial are different contexts, though, and can warrant different approaches.

Yeah definitely, and even another set of trade offs for Redwood books 😉

**Comment by Tobbe** [comment]
> Yeah definitely, and even another set of trade offs for Redwood books 😉

Ohhhh! Do I see a @jtoar vs @ajcwebdev book fight in the future? 🥊 🤣

**Comment by ajcwebdev** [comment]
He can take the Apollo section 😆

**Comment by pi0neerpat** [comment]
+1 for making the new developer on-boarding as simple as possible. I am a bit worried that we are creating two paths, which may lead to other issues. 

1. **Postgres-before-deployment** 
2. **Postgres-from-the-beginning** 

Experienced devs will start to always take `#2`, and attention/focus will not be given to `#1`. New devs may struggle on `#1`, but its not something experienced devs encounter often. Thus, there aren't many who can help.

Whatever the solution is, I think its a good idea to not encourage  `#2` (such as in demos). It should be _so easy_ to hack away on a new project and then do `#1`, that everyone always waits until deployment.

**Comment by ajcwebdev** [comment]
That's a good point, maybe include a title like "Redwood Tutorial: Expert Mode" or something like that to encourage newer developers to stick with the official tutorial.

I try to run through the actual tutorial every release, so even with this other version I'm working on I'd still devote time to make sure the actual tutorial works well.

I think having two different flows like this can lead to catching more bugs not less because we're putting the material to the test with a wider range of use cases. Totally agree that it will lead to confusion, though.

**Comment by ajcwebdev** [comment]
[Here's a link to the demo I did for Async, might be still processing if you click it in the next half hour](https://www.youtube.com/watch?v=R5p3Xdmkiws).

Feel free to check it out and if we decide we don't want to pursue this direction and think it will be confusing to the community then I would be happy to continue working offline with the idea of publishing it in the form of some sort of e-book or potentially real book in the future where it's clear it's totally separate from the current tutorial.

**Comment by thedavidprice** [comment]
- I 100% vote to keep the tutorial flow **as is**
- I fixed (and merged) the Postgres Doc "Migrations" section here: https://github.com/redwoodjs/redwoodjs.com/pull/616
- ⚠️ SHADOW DB 😈: If you want to use a hosted/cloud DB for dev, it requires **2** hosted DBs. ('Cause Prisma.)
  - See [Prisma v2.17.0 Release Notes](https://github.com/prisma/prisma/releases/tag/2.17.0)
  - "Prisma Migrate now works with cloud-hosted databases" --> `... shadowDatabaseUrl = env("SHADOW_DATABASE_URL") ...`

**Comment by ajcwebdev** [comment]
Thanks David, those docs look great! I'll go ahead and close this issue and if anyone else runs into issues we can point them here.
