### ISSUE TITLE
Proposal for more information in Tutorial I

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwoodjs.com#627]
The component `web/src/components/BlogPostCell/BlogPostCell.js`

<div align="center">
  <img src="https://user-images.githubusercontent.com/2712405/111036080-6893c500-83eb-11eb-9c24-b05aef6f441d.png"> <br>
</div>
<p/>

Is there any significance of using `$`? If so, it should be explained otherwise it would be better to use something else (people that know jQuery would expect this to be a global variable)

**Comment by cannikin** [comment]
This is how GraphQL denotes variables. We say at the beginning of the tutorial that we're not going teach all of the basics of all the technologies we're using (GraphQL, React, databases) but that you can follow along and get the gist of what we're doing.

Notice that the GraphQL section is all one giant multi-line string, so these wouldn't be interpreted as variables even if we *were* using jQuery. I'd be surprised if 10% of Redwood's current user base has ever used jQuery, though. For many it seems like React *is* Javascript as far as they're concerned!

**Comment by adriatic** [comment]
> We say at the beginning of the tutorial that we're not going to teach all of the basics of all the technologies we're using (GraphQL, React, databases) but that you can follow along and get the gist of what we're doing.

That is a fair assessment; thanks for a free tip o GraphQL.
