### ISSUE TITLE
Proposal to improve the Tutorial text

### ISSUE THREAD

**Issue by adriatic** [redwoodjs/redwoodjs.com#628]
Hellp, @cannikin 

I could create a PR for this - but I do have respect for your text writing skills, so this is just a proposal

![image](https://user-images.githubusercontent.com/2712405/111039336-8cf79d80-83fb-11eb-9623-b690a7ac7e52.png)

**Comment by cannikin** [comment]
Ahhh good catch. I'd probably change that second sentence to:  "We won't be retrieving records from the database in our Contact form so we won't create a cell."

A PR would be appreciated!

**Comment by adriatic** [comment]
A great alternative - PR coming up
