### ISSUE TITLE
Update docs with options for `makeMergedSchema`

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwoodjs.com#645]
Need to document the `makeMergedSchema` options somewhere (see https://github.com/redwoodjs/redwood/pull/1964) 

Suggesting add content to https://redwoodjs.com/docs/graphql.html#the-root-schema

**Comment by dthyresson** [comment]
@dac09 and @thedavidprice with 0.37, the `graphql.ts` function in your app no longer exposes `makeMergedSchema`.

See: https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/template/api/src/functions/graphql.ts

We have a new way of passing in schema directives (see redwoodjs/redwood#1964).

I'm not sure `makeMergedSchema` needs external docs. Thoughts?

**Comment by dac09** [comment]
Agreed, probably an internal detail we don't need to expose anymore :)
