### ISSUE TITLE
Update tutorial directory structure screenshot/description to include api/src/lib/db.js

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#65]
https://github.com/redwoodjs/create-redwood-app/issues/45

**Comment by jrhorn424** [comment]
Happy to help with this. Do I need specific color scheme or font?

**Comment by cannikin** [comment]
I updated the title of this issue to be more accurate!

This is something new we released in 0.3.0 where the initialization of the `db` variable you use in the services happens in this file (instead of internal to Redwood) so that you can pass the constructor some options if you want. I was going to add a bulletpoint to the breakdown of what's in the `api` directory, describing the above.

I also deleted all the directories that I wasn't actively discussing so that the screenshot was nice a tidy and didn't show a bunch of random config files, `node_modules` directory, etc. I'm using the "Material Theme Darker High Contrast" in the rest of my screenshots. The directory structure font is just whatever the default is for VS Code on the Mac.

**Comment by jrhorn424** [comment]
Would you accept a PR with those changes? I'd also propose that instead of screenshots, we use an edited version of the output from a GNU `tree` command? It's formatted nicely. You might be able to get a sense of what it's like by installing `tree` with homebrew and trying it inside a project.

**Comment by cannikin** [comment]
Yep we'd happily take a PR as long as the text fits in the with the "feel" of the tutorial. :)

And I could be persuaded to use some `tree` output, I love `tree`!

**Comment by cannikin** [comment]
Done! Used output of `tree` per @jrhorn424's recommendation!
