### ISSUE TITLE
Homepage redesign in preparation of 1.0

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#713]
I played around with a new homepage design a couple of months ago, opened it as a draft PR, and then forgot about it while other things took priority. 

Some things we'd like to accomplish with this redesign:

* New tagline: "Bringing full-stack to the Jamstack" seems too narrow of a focus now, Redwood is more than that. @mojombo  mentioned it being more like a "super framework"
* Move the docs to our learn.redwoodjs.com codebase: it's built on Docusaurus 2.0 and has a great I18n setup where people can collaborate on translations via https://crowdin.com/ We'd probably transition the subdomain to docs.redwoodjs.com
* redwoodjs.com becomes more of a "marketing" site and launchpad to other, focused sites: docs, shop, community...
* We talked about adding Testimonials to the homepage
* Call out of "who uses Redwood" (companies or other projects)
* Call out of sites built with Redwood (Everfund, Snaplet)
* An [open issue](https://github.com/redwoodjs/redwoodjs.com/issues/395) for adding a dedicated **Contributors** page
* We've still got an [open issue](https://github.com/redwoodjs/redwoodjs.com/issues/581) to create a **Jobs** page
* Another [open issue](https://github.com/redwoodjs/redwoodjs.com/issues/580) to add a **Recent Tweets** widget

The site is currently built on a custom "framework" (https://github.com/cannikin/cameronjs) that just combines regular ol' HTML into a static site. This seems to scare some people who have only ever worked in React world. There is no reason for this plain, flat website to load megabytes of Javascript and consume gigabytes of RAM just to display text! It's [just a website](https://justinjackson.ca/words.html).

Here's my first stab at a purely visual redesign and only takes into account a couple of the concerns above. Some of the code snippets could probably be updated, but I think we like the idea of showing the actual code rather than some **Enterprise Solutions** website that uses a bunch of marketing fluff to try and convince you to use it. It could be neat to include some GIFs showing something like going from a blank page to a scaffolded model with a single CLI command.

![127 0 0 1_8080_](https://user-images.githubusercontent.com/300/121227138-1c1c2200-c840-11eb-8b22-142703866729.png)

**Comment by cannikin** [comment]
Brainstorming a new message for the hero section...

* One API, multiple clients (web, mobile, Electron, CLI...)
* Edge-ready
*

**Comment by georgewritescode** [comment]
I'm not sure typescript is mentioned there. 
In the description we could add typescript to the list Redwood is build on.
We could also add a typescript toggle to the code snippets.

**Comment by sarthaktexas** [comment]
is this still something that needs help?

**Comment by sarthaktexas** [comment]
> Brainstorming a new message for the hero section...
> 
> * One API, multiple clients (web, mobile, Electron, CLI...)
> * Edge-ready

database-ready jamstack framework?

**Comment by cannikin** [comment]
> database-ready jamstack framework?

We're trying to move away from "jamstack"...there's a lot of baggage around CRM-backed applications with no use for a database. Not sure if we should be inventing something new, or just a better combination of terms... "edge-ready javascript framework" or something similar...

**Comment by sarthaktexas** [comment]
that makes sense

**Comment by dac09** [comment]
Hey @cannikin - had a couple of points worth considering

**a) Longer docs**
one of my pet peeves with our current docs is when the document is super long, it feels very overwhelming and hard to know where you are on the page. I don't have a suggestion for this, but we should maybe think about how to improve this experience

**b) More ways to provide context in the code blocks**
There's an excellent blog post on this: https://ped.ro/blog/code-blocks-but-better
I think in particular being able to highlight parts that we're explaining on hover, would be a huge positive

The other thing that is also worth exploring, https://shikijs.github.io/twoslash/ - the name/website seems confusing, but its seems like a very powerful tool

**Comment by sarthaktexas** [comment]
For the longer docs thing, can't we just add like a progress bar/circle type thing? I feel like to would help readers gauge where they are.

**Comment by cannikin** [comment]
Some more ideas for pitching Redwood from @mojombo during a core meeting:

* RedwoodJS is the framework for serious work
* Next.js for your weekend project, Redwood for your startup
* Will end up saving thousands of dev hours
* Maybe tell the “workflow story": starting from Storybook, build front end, plug in backend
* Design-oriented workflow
* We probably can’t beat Next.js for the quick, weekend/hackathon project

**Comment by sarthaktexas** [comment]
I love the first two!

**Comment by sarthaktexas** [comment]
> Some more ideas for pitching Redwood from @mojombo during a core meeting:
If it's possible, I'd love to talk about these non-async (sync sounds weird lol)

**Comment by georgewritescode** [comment]
> Got some testimonials on the page finally...easy to update too, just edit TESTIMONIALS.md in the root:
> 
> ![image](https://user-images.githubusercontent.com/300/131046043-b5fbfb29-f632-4422-9e00-22a5c3112a05.png)

Looks great!

For me the 'hero' paragraph is a tad long for new viewers. 
I think cutting the last two sentences and adding to the prior sentence 'ready to go and ready to scale' would deliver a similar message. We could break up the messages in the sentence with 'Redwood is pre-configured with React, GraphQL, Primsa, Storybook, Jest and more, ready to go and ready to scale. 

Regarding the last sentence, from my perspective, as an opinionated framework, emphasizing Redwood working for your workflow is not targeted at the framework as it encourages you to change your workflow to a view of best practice.

Open to that others may read it differently

**Comment by jacebenson** [comment]
I started to look at this... last night and I should have commented then.  The site generator you're using is.. very different from what I've seen.  Anyways, I thought, "Wouldn't it be fun to re-create what @cannikin did in 11ty?"  So I did.  (maybe it will not scare folks away from contributing)

If your not opposed to it, I can make a PR.  I looked over you're build and noticed the following things were missing.
- [ ] News Page
- [ ] Job Page (on hold per another issue - waiting for direction from someone)
- [ ] Who Uses redwood page/section
- [ ] Contributors page
- [ ] Add recent tweets widget somewhere

I created 

- [x] News page
- [ ] Thought about the Job Page, that's tough one
- [x] Contributors page (do we want to list all /redwood/redwoodjs and redwood/redwoodjs.com contributors together?) **needs more work** /contributors
- [x] Used by section (do we have a list somewhere for this?) **needs more work at bottom of home page**
- [x] I borught over the docs/cookbooks/video pages but I think that will be pulled for learn.redwood.com links.

Here's the stood up site https://hopeful-perlman-34ea32.netlify.app/ and the repo https://github.com/jacebenson/redwoodjs.com

**Comment by cannikin** [comment]
Hey, that's CameronJS, the best framework ever! https://cameronjs.com/ Never got around to building out the actual site. 😬

I just have visceral negative reaction to using something like React for a static site. Even something like Gatsby, which will make a static site at the end of the day…someone tried that at one point and it was like a 10 minute deploy process, just to end up with flat HTML. 😕  Which, I guess, who cares because it’s running in CI, but it’s the principle of the thing! We walked to school uphill 5 miles in both directions in the snow, and we liked it!

Up until the Jobs thing there wasn’t ever a need for any dynamic data. Although I’m still on the fence about the job board because I feel like it’ll take manual input on our side to keep it up-to-date, and eternal vigilance is not something humans are good at, mostly the “eternal” part haha 

But maybe moving it to something like 11ty will enable more maintainers getting involved? Although I don't know that the framework was really stopping anyone, we didn't see any Issues asking how to get started or anything. I think not many people want to write docs, everyone just wants to write code!

**Comment by ajcwebdev** [comment]
11ty has nothing to do with React, it's a static site generator modeled on Jekyll but with Node instead of Ruby. The creator works for Netlify so I would image the builds are well optimized. It doesn't support dynamic data beyond the experimental new [serverless feature](https://www.11ty.dev/docs/plugins/serverless/), if you wanted to use something like React with it you would need something like [Slinkity](https://slinkity.dev/) which is still extremely new. If we are going to use any kind of SSG, homerolled or not, 11ty is a no brainer.

**Comment by jacebenson** [comment]
@cannikin I've been thinking about the job board thing.  I think either we should drop it until you and @mojombo decide how you want to have that as managing posts/users and such seems like a drag.  If folks could post jobs on something like indeed.com or whatever an api hit would be no problem.

**Comment by cannikin** [comment]
We had a core team meeting last week and we think we'll build a Jobboard for the 1.0 release! You'll be able to post job listings, so it'll be up to people to come and create them, we're not going to have anyone going through job boards looking for Redwood jobs and copying them to this site or anything. And it'll be built with Redwood!

**Comment by garfield7878** [comment]
> 

I appreciate all the work that is being done and that it is the core team's project, however, could the job board wait until after v1 as a non-critical add on? 
We are already well past all indicative timelines given for a v1 and not being v1 creates real barriers for people using Redwood such convincing people it is mature enough to use (particularly non-technical people)

**Comment by noire-munich** [comment]
> We had a core team meeting last week and we think we'll build a Jobboard for the 1.0 release! You'll be able to post job listings, so it'll be up to people to come and create them, we're not going to have anyone going through job boards looking for Redwood jobs and copying them to this site or anything. And it'll be built with Redwood!

I've been looking forward to this one, great :+1: 

> We are already well past all indicative timelines given for a v1 and not being v1 creates real barriers for people using Redwood such convincing people it is mature enough to use (particularly non-technical people)

@garfield7878 V1 for nodejs, apollo graphql, react, typescript, storybook and almost 95% of what is used by Redwood happened years ago. Do those non-technical people know about the startups building with Redwood? What numbers would actually convince them? What do they, as non-technical people, expect from a RedwoodJS V1?

**Comment by jtoar** [comment]
New site is live! You can find the code at https://github.com/redwoodjs/sprout.
