### ISSUE TITLE
Docs - Quick Start - Update current versions of Node and Yarn required

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwoodjs.com#717]
In https://redwoodjs.com/docs/quick-start

![image](https://user-images.githubusercontent.com/1051633/121819015-d3f26a80-cc58-11eb-8c6b-069595ce1bc8.png)

```
RedwoodJS requires Node.js (>=12) and Yarn (>=1.15).
```

An issue was raided here in Community https://community.redwoodjs.com/t/best-way-to-start-contributing/85/10?u=dthyresson about installing Prisma with v12.

Should these docs be updated to use Yarn 1.18 and Node 14.7.0 (or lts)?

**Comment by thedavidprice** [comment]
Good catch, because we pin it in the package.json via `"node": "14.x",` we should just say
- `RedwoodJS requires Node.js (=14.x) and Yarn (>=1.15)`

The Tutorial has it as `>=14` which is not correct (15 and 16 will error).

**Comment by thedavidprice** [comment]
- .com PR here #719
- tutorial PR here https://github.com/redwoodjs/learn.redwoodjs.com/pull/124

@dthyresson I've requested your review on both
