### ISSUE TITLE
Cookbooks - File Uploads - filestack-react has been deprecated

### ISSUE THREAD

**Issue by 0x1a4f7d58** [redwoodjs/redwoodjs.com#731]
filestack-react has been deprecated 
https://www.npmjs.com/package/react-filestack

Cookbook code no longer works :/
https://github.com/redwoodjs/redwoodjs.com/blob/main/cookbook/File_Upload.md

Looks like should be using this instead:
https://github.com/filestack/filestack-react#usage

**Comment by thedavidprice** [comment]
Thanks for letting us know about this @0x1a4f7d58 Curious if you've tried to implement with `filestack-react` and/or if you'd be available to help us update this article?

Looping in @cannikin (who I believe created this cookbook).

**Comment by cannikin** [comment]
Dammit, their old React code just *doesn't work* any more? Something about their API must have changed? But there must be thousands of integrations with that old package...did everyone's site just stop working?

Just double checked and an old integration I have (from about a year ago) and it still works! Maybe there's some versioning built in somehow?

**Comment by dthyresson** [comment]
I recently used Filestack (a few months ago) in a project and I just checked and was using 

```
    "filestack-react": "^4.0.0",
```

And this is in a RW app.

```js
import { PickerOverlay } from 'filestack-react'

// ...

                  <PickerOverlay
                    apikey={process.env.FILESTACK_API_KEY}
                    pickerOptions={{
                      accept: [
                        'application/zip',
                        'application/gzip',
                        'application/zip, application/octet-stream',
                        'application/x-zip-compressed',
                        'application/x-zip',
                      ],
                      allowManualRetry: true,
                      fromSources: ['local_file_system'],

//...
```

And works fine.

So, yes, the Cookbook does need updating.

**Comment by watway** [comment]
I just ran through the File Uploads recipe and didn't have a problem.  `react-filestack` has been deprecated, but the recipe already refers to `filestack-react`, which has not been deprecated.

**Comment by jtoar** [comment]
Thanks @watway, I recently updated the cookbook but forgot to close this issue—doing so now!
