### ISSUE TITLE
PM2 error when trying to deploy on Windows instead of Linux

### ISSUE THREAD

**Issue by ajcwebdev** [redwoodjs/redwoodjs.com#765]
From Discord discussion with @bshea5:

> I'm getting `The syntax of the command is incorrect` but it's not clear what syntax is incorrect. I've replaced forward slashes with double back slashes in the pm2.config, but not sure what else to do beyond that.

![pm2-deploy-error](https://user-images.githubusercontent.com/12433465/128254492-1d18fb29-1402-410e-8979-51c4f63133aa.png)

### Workaround

> If anyone else runs into this issue, I was able to fix by changing the default shell used by OpenSSH to Git Bash instead of CMD. That got rid of the syntax issue. Still have to try out other commands, but it was able to run and clone my sample repo at least. Opened a ticked for [pm2-deploy](https://github.com/Unitech/pm2-deploy/issues/198).

**Comment by ajcwebdev** [comment]
@bshea5 do you know if this is still a problem or can we close this issue out?

**Comment by bshea5** [comment]
Thanks for checking @ajcwebdev .  For me personally, it's not an issue anymore since I've moved on from the project. I can't confirm if it still occurs.

**Comment by ajcwebdev** [comment]
Okay, thanks for the follow up. Since we've got a documented work around I'll close this out and anyone else is free to comment and let us know to open it back up if they want to dig into finding a fix for the default shell.
