### ISSUE TITLE
Document Workaround for `Cannot find module` error in Netlify functions when deploying and building with esbuild

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwoodjs.com#766]
See issue: https://github.com/redwoodjs/redwood/issues/3216

There is an issue when building with `esbuild` on in the `redwood.toml` and then when Netlify builds functions.

At runtime, the functions report an error with `Cannot find module  '@babel/runtime-corejs3/core-js/object/define-property'`.

The workaround is to disable esbuild when deploying.

So, this workaround might be added to help troubleshoot.

Add to Netlify deploy, with a callout: https://redwoodjs.com/docs/deploy#netlify-deploy

And here for esbuild tool config: https://redwoodjs.com/docs/app-configuration-redwood-toml.html#esbuild

Note: This may not be a 100% workaround, but could be worth documenting that will need to add the dependency as well.

> In our case was failing with both esbuild = false and true. The only solution was to add dependencies to the API side.

**Comment by dac09** [comment]
Note that v0.36 changes how API files are transpiled slightly.

I think this issue started happening since our repo re-organisation. My understanding:

We're using `@babel/plugin-transform-runtime` as a framework dep, used at BUILD time.

In the docs
> This is where the @babel/plugin-transform-runtime plugin comes in: all of the helpers will reference the module @babel/runtime to avoid duplication across your compiled output. The runtime will be compiled into your build.

but in a small section they also mention:
> The transformation plugin is typically used only in development, but the runtime itself will be depended on by your deployed code. See the examples below for more details.

So solution I think maybe to add the runtime dependency to `@redwoodjs/api`

**Comment by thedavidprice** [comment]
To be closed when redwoodjs/redwood#3220 is merged
