### ISSUE TITLE
Serverless Documentation should include serving binary data example

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwoodjs.com#771]
See: https://github.com/redwoodjs/redwood/pull/3219

Support was added to return Base64 encoded binary data as described in https://aws.amazon.com/blogs/compute/handling-binary-data-using-amazon-api-gateway-http-apis/

These serverless docs could use a quick description of how/why to return binary data and base64 encoding.

**Comment by dthyresson** [comment]
@corbt You you be able to write up short docs on your PR to support binary data? Thanks.

**Comment by corbt** [comment]
cc @dthyresson
