### ISSUE TITLE
Cells Documentation refers to predictcovid.com but visiting site issues security warnings

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/redwoodjs.com#776]
See the Loading section of the Redwood cells docs:

https://redwoodjs.com/docs/cells#loading

> For a production example, navigate to predictcovid.com, the first site made with Redwood

![image](https://user-images.githubusercontent.com/1051633/129416639-3fbdaa64-b893-4384-9a32-c27ee9c139a1.png)

When visiting the site, my eero firewall won't let me visit due to securing issues:

![image](https://user-images.githubusercontent.com/1051633/129416666-6080e954-d47d-4380-af01-810a59b07941.png)

Need a new example or remove?

**Comment by thedavidprice** [comment]
+1 remove
