### ISSUE TITLE
Update to Many-to-Many Definition example in Redwood Docs

### ISSUE THREAD

**Issue by bshea5** [redwoodjs/redwoodjs.com#777]
Version: 0.35.2
OS: Windows

Regarding the documentation for schema relations, [schema-relations](https://redwoodjs.com/docs/schema-relations)

While attempting to define a many to many relationship using the Redwood docs, I ran into a problem. 
```
error: Error validating field sites in model EventsOnSites: The relation field sites on Model EventsOnSites is missing an opposite relation field on the model Site. Either run prisma format or add it manually.
```

I'd get this in running the migration, but also in my linting results.

I consulted Discord and @dthyresson told me to check out the Prisma docs to see if anything has changed. Now I can't say if anything has changed yet, I've only just started using Prisma and Redwood, but the example on their docs varies from what is on the Redwood docs.

===

Redwood Docs:
``` prisma
model Product {
  id       Int      @id @default(autoincrement())
  title    String
  desc     String
  tags     Tag[]
}

model Tag {
  id       Int       @id @default(autoincrement())
  name     String
  products Product[]
}

model ProductsOnTags {
  id        Int       @id @default(autoincrement())
  tagId     Int
  tags      Tag[]     @relation(fields: [tagId], references: [id])
  productId Int
  products  Product[] @relation(fields: [productId], references: [id])
  @@unique([tagId, productId])
}
```

===

Prisma Docs:
``` prisma
model Post {
  id          Int                 @id @default(autoincrement())
  title       String
  categories  CategoriesOnPosts[]
}

model Category {
  id    Int                 @id @default(autoincrement())
  name  String
  posts CategoriesOnPosts[]
}

model CategoriesOnPosts {
  post        Post     @relation(fields: [postId], references: [id])
  postId      Int       // relation scalar field (used in the `@relation` attribute above)
  category    Category @relation(fields: [categoryId], references: [id])
  categoryId  Int      // relation scalar field (used in the `@relation` attribute above)
  assignedAt  DateTime @default(now())
  assignedBy  String

  @@id([postId, categoryId])
}
```

===

When switching to Prisma's example, I am able to run a migration with my models.

Do the docs need updating or is there something else I'm missing in Redwood's procedure or methodology?

**Comment by bshea5** [comment]
Follow up: When I used `g scaffold` with the above models I got: 
 ┌─────────────────────────────────────────────────────────────────────────┐ 
 │                                                                         │ 
 │   WARNING: Cannot generate CRUD SDL without an `@id` database column.   │ 
 │                                                                         │ 
 │   If you are trying to generate for a many-to-many join table           │ 
 │   you'll need to update your schema definition to include               │ 
 │   an `@id` column. Read more here:                                      │ 
 │   https://redwoodjs.com/docs/schema-relations                           │ 
  × Generating scaffold files...                                             
    → Failed: Could not generate SDL                                         
    Adding layout import...                                                  
    Adding set import...                                                     
    Adding scaffold routes...                                                
    Adding scaffold asset imports...
Failed: Could not generate SDL

===

So I adjusted the linker model like so, more according to the current Redwood docs:
``` prisma
model EventOnSite {
  id        Int       @id @default(autoincrement())
  event     Event     @relation(fields: [eventId], references: [id])
  eventId   Int       // relation scalar field (used in the `@relation` attribute above)
  site      Site      @relation(fields: [siteId], references: [id])
  siteId    Int       // relation scalar field (used in the `@relation` attribute above)

  @@unique([eventId, siteId])
}
```
Afterwards, I was able to scaffold all three models.

**Comment by dthyresson** [comment]
So, the code sample on the docs site is out of date and does give an error:

![Screen Shot 2021-08-14 at 13 48 46](https://user-images.githubusercontent.com/1051633/129456109-c3dfd832-b37b-41c0-b5b5-bc7e90dbfb23.png)

But, there is a subtle difference between the Product and Tag and the Post and Category many-to-many explicit example.


Notice that `ProductsOnTags` has **products** and tags** plural -- an array list of them ...

```
model Product {
  id    Int              @id @default(autoincrement())
  title String
  desc  String
  tags  ProductsOnTags[]
}

model Tag {
  id       Int              @id @default(autoincrement())
  name     String
  products ProductsOnTags[]
}

model ProductsOnTags {
  id        Int       @id @default(autoincrement())
  tagId     Int
  tags      Tag[]     @relation(fields: [tagId], references: [id])
  productId Int
  products  Product[] @relation(fields: [productId], references: [id])

  @@unique([tagId, productId])
}
```

Whereas `CategoriesOnPosts` has just one post and one category.

This is why there is no id on `CategoriesOnPosts` and it is join table that you'd never scaffold ... it simply connects the posts and categories.

```
model Post {
  id         Int                 @id @default(autoincrement())
  title      String
  categories CategoriesOnPosts[]
}

model Category {
  id    Int                 @id @default(autoincrement())
  name  String
  posts CategoriesOnPosts[]
}

model CategoriesOnPosts {
  post       Post     @relation(fields: [postId], references: [id])
  postId     Int // relation scalar field (used in the `@relation` attribute above)
  category   Category @relation(fields: [categoryId], references: [id])
  categoryId Int // relation scalar field (used in the `@relation` attribute above)
  assignedAt DateTime @default(now())
  assignedBy String

  @@id([postId, categoryId])
}
```

In the Products and Tags, there is a list .. so in needs an id -- and that can be scaffolded.

They are just two different ways of modeling the relationship.

@cannikin what do you think we should do with the example? We definitely need to update ti so it is a valid example, but  should we have a schema like:


```
-- CreateTable
CREATE TABLE "Product" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "desc" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Tag" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "ProductsOnTags" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "tagId" INTEGER NOT NULL,
    "productId" INTEGER NOT NULL,
    FOREIGN KEY ("tagId") REFERENCES "Tag" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "_ProductToProductsOnTags" (
    "A" INTEGER NOT NULL,
    "B" INTEGER NOT NULL,
    FOREIGN KEY ("A") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ("B") REFERENCES "ProductsOnTags" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "_ProductsOnTagsToTag" (
    "A" INTEGER NOT NULL,
    "B" INTEGER NOT NULL,
    FOREIGN KEY ("A") REFERENCES "ProductsOnTags" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ("B") REFERENCES "Tag" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "ProductsOnTags.tagId_productId_unique" ON "ProductsOnTags"("tagId", "productId");

-- CreateIndex
CREATE UNIQUE INDEX "_ProductToProductsOnTags_AB_unique" ON "_ProductToProductsOnTags"("A", "B");

-- CreateIndex
CREATE INDEX "_ProductToProductsOnTags_B_index" ON "_ProductToProductsOnTags"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_ProductsOnTagsToTag_AB_unique" ON "_ProductsOnTagsToTag"("A", "B");

-- CreateIndex
CREATE INDEX "_ProductsOnTagsToTag_B_index" ON "_ProductsOnTagsToTag"("B");
```

or more like:


```
-- CreateTable
CREATE TABLE "Post" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Category" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "CategoriesOnPosts" (
    "postId" INTEGER NOT NULL,
    "categoryId" INTEGER NOT NULL,
    "assignedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assignedBy" TEXT NOT NULL,

    PRIMARY KEY ("postId", "categoryId"),
    FOREIGN KEY ("postId") REFERENCES "Post" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ("categoryId") REFERENCES "Category" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

```

The latter is closer to

![image](https://user-images.githubusercontent.com/1051633/129456266-7901dbce-7376-433e-814a-ef1696fcc1dd.png)


but not exact.

But @bshea5 the reason you cannot scaffold `EventOnSite ` is because as you noticed, you need an id. But, you don't really need an SDL or a UI for that -- instead, your mutations will connect or create to join.

See Prisma nested writes: 

https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide#nested-writes


and the idea of `connect` or `connectOrCreate` or `create`:

https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#connectorcreate

**Comment by cannikin** [comment]
It looks like Prisma changed their docs around...the link for many-to-many relationships in our doc should go here now: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations/ That one explains the difference between implicit and explicit, and it says in our docs, you can only scaffold an *explicit* many-to-many (and it has to have an `id` column).

Looks like the snippet defining `schema.prisma` for the explicit many-to-many should be:

```
model Product {
  id       Int      @id @default(autoincrement())
  title    String
  desc     String
  tags     ProductsOnTags[]
}

model Tag {
  id       Int       @id @default(autoincrement())
  name     String
  products ProductsOnTags[]
}

model ProductsOnTags {
  id        Int     @id @default(autoincrement())
  tagId     Int
  tag       Tag     @relation(fields: [tagId], references: [id])
  productId Int
  product   Product @relation(fields: [productId], references: [id])
  @@unique([tagId, productId])
}
```

...and then you should be able to scaffold all three models and the docs should make sense again! 

Or is there a bigger problem that I'm overlooking?

**Comment by bshea5** [comment]
Unless there is something else under the hood going on, updating it to match the prisma docs works for my project. I was able to scaffold all three models.

**Comment by thedavidprice** [comment]
@bshea5 great to hear! Thanks for reporting back with the update.

If anyone is available to update this doc on the site, the help would be greatly appreciated!

**Comment by cannikin** [comment]
I thought for sure I already made this change in the docs, but I don't see it there now...maybe I'm just thinking of that code snippet above. Should be pretty simple to plug that into the docs and just update a couple blocks of text nearby. I can come back around to it if no one grabs it soon.

**Comment by shansmith01** [comment]
Happy to update. First time contributing. 

Working out many-to-many relationships has been challenging so far. I May have to fire off a few more issues yet, but happy to make that doc pretty comprehensive if we can it sorted

**Comment by shansmith01** [comment]
So I have just attempted to use [the snippet above ](https://github.com/cannikin) and I can not generate a scaffold for ProductsOnTags. I get the following error

<img width="699" alt="Screen Shot 2021-09-09 at 3 03 16 PM" src="https://user-images.githubusercontent.com/1866452/132615511-2f3236a7-b349-4a08-89aa-9079dd235c70.png">

I attempted to generate a scaffold and also just generate an SDL with no luck

Over in my produts.sdl.js productsOnTags is an unknown type

<img width="482" alt="Screen Shot 2021-09-09 at 3 06 41 PM" src="https://user-images.githubusercontent.com/1866452/132615832-7e0e5644-6ec0-4dfb-9c9b-375ad1d3cb5d.png">

**Comment by shansmith01** [comment]
Okay, and the culprit was the productsontags having an s on the end. So the correct code is

```
model Product {
  id    Int             @id @default(autoincrement())
  title String
  desc  String
  tags  ProductsOnTag[]
}

model Tag {
  id       Int             @id @default(autoincrement())
  name     String
  products ProductsOnTag[]
}

model ProductsOnTag {
  id        Int     @id @default(autoincrement())
  tagId     Int
  tag       Tag     @relation(fields: [tagId], references: [id])
  productId Int
  product   Product @relation(fields: [productId], references: [id])

  @@unique([tagId, productId])
}
```

**Comment by bshea5** [comment]
Sounds right. I had to define mine as singular as well(no 's'). Thanks for updating the docs.

**Comment by cannikin** [comment]
Whoops, sorry! 😃 Thanks for updating the docs, I’ll review in the morning!

**Comment by cannikin** [comment]
Merged, thanks!
