### ISSUE TITLE
Scroll issue on mobile menu

### ISSUE THREAD

**Issue by KrisCoulson** [redwoodjs/redwoodjs.com#852]
https://user-images.githubusercontent.com/6943688/138221081-74b3644e-3abd-46c7-9623-fec223060e09.MOV

If you view the site on mobile open the menu and then scroll by placing your finger where the logo is the recorded issue will happen. If you just scroll on the menu it seems to work fine.

**Comment by jtoar** [comment]
Closing this as the website is brand new!
