### ISSUE TITLE
Redwood's Resolver Args link not working

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/redwoodjs.com#939]
![image](https://user-images.githubusercontent.com/30793/148677240-7bf3851e-b0ef-4513-9d26-b111f1899216.png)

There's a link to "Redwood's Resolver Args" in the right hand side menu at https://redwoodjs.com/docs/graphql but it's not working.

It links to https://redwoodjs.com/docs/graphql#redwood-s-resolver-args but the proper target should be https://redwoodjs.com/docs/graphql#redwoods-resolver-args (`redwoods` vs `redwood-s`)

**Comment by cannikin** [comment]
Regex to the rescue!

**Comment by Tobbe** [comment]
![image](https://user-images.githubusercontent.com/30793/151969376-31a34f86-b7f0-45b5-8e47-195ccd09a32d.png)
