### ISSUE TITLE
Cookbook: send an email

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/redwoodjs.com#94]
GraphQL call that triggers an email via SendGrid.

We could also use this as an example of using one service inside another. Have a `log` table that logs sends. GraphQL call goes to a custom `emails.js` service, which imports `logs.js` service and creates the log entry.

**Comment by dthyresson** [comment]
Even fancier (and incorporating the cron background job recipe idea) would be to:

* generate email
* persist email in a message q (in this case a table not a Redis q or other q)
* background cron job call function to send unsent messages (even 10 mins or so for testing)
* logs message sent (or if mail api call failed ... "reschedule")

I've used [Mailgun to send](https://documentation.mailgun.com/en/latest/api-sending.html#sending) quite a bit and solid experience --  [sdk](https://www.npmjs.com/package/mailgun-js)

**Comment by jtoar** [comment]
Another chance to showcase [repeater.dev](repeater.dev)? #110

**Comment by cannikin** [comment]
I thought this particular recipe should have the fewest number of external dependencies possible, ideally just the external mail service. I was planning on a SendGrid integration that's triggered by a custom Service (not backed by the database). As mentioned in the description that service would call the `logs` service (which *is* backed by the database) and would showcase one service using another (something @mojombo has been wanting to demonstrate for a while).

The Background Job recipe could then maybe build off of this one by sending the emails asynchronously...

**Comment by jtoar** [comment]
That sounds great, excited to add a bona fide example of a service using a service.

**Comment by jtoar** [comment]
@cannikin This would be a great one to do given the recent Discord activity

**Comment by Tobbe** [comment]
@cannikin I created a PR for a email recipe for our cookbook. https://github.com/redwoodjs/redwoodjs.com/pull/945

It's not exactly what's discussed here (it's not calling one service from another). TBH I don't fully understand the logging stuff here. Wouldn't you just use @dthyresson's Logger for logging? Possibly sending the logs to LogDNA or Logtail or something like that?

**Comment by cannikin** [comment]
It was a bit of a contrived example, but the idea was to have an audit trail in the database so that, for example, users could have a viewable/searchable list of sent emails in the app itself, instead of a logging stream for developer debugging. You could go to a "History" tab or something and see a list of all the emails that the app sent to/from you.

It wasn't the original intention of the email cookbook to do that, but after talking with Tom we thought that creating an audit trail would be a reasonable example of having one service (email) call another (audit/history).

**Comment by Tobbe** [comment]
Solved by #949
