### ISSUE TITLE
Docs: TypeScript documentation needs more information!

### ISSUE THREAD

**Issue by guledali** [redwoodjs/redwoodjs.com#971]
**TypeScript Page** needs more info for newcomers, for example how to use it in conjunctions with redwood `cells`

> How do I share types between backend to frontend and so forth?
> How does a typical redwood component with typescript look?

Add sample code for backend and frontend, query and the mutations for the frontend code

@thedavidprice @cannikin @dthyresson @mojombo

**Comment by jtoar** [comment]
Hey @guledali, that doc is fairly short and should definitely have an example of Cells like you said, but as far as sharing types between sides goes, does this section not cover it for you? https://redwoodjs.com/docs/typescript#sharing-types-between-sides.

**Comment by guledali** [comment]
Okay I missed it somehow when I originally glanced over the text😁 my bad, but I still think it's needs more a demonstration then maybe some code snippets to look at.

**Comment by jtoar** [comment]
We'll be adding a lot more TS docs in https://github.com/redwoodjs/redwood/pull/5491.
