### ISSUE TITLE
Should mention somewhere that redwood ships with an awesome db gui called prisma studio!

### ISSUE THREAD

**Issue by guledali** [redwoodjs/redwoodjs.com#975]
Redwood.js has a quick access for a db-viewer called prisma studio, easily accesible by typing in the rool level of any redwood project

```sh
      yarn rw prisma studio
```

Although this falls under the umbrella of prisma, I still however think somewhere in the redwood.js docs there should be a mention of this. It comes from personal experience but I have been in teams where everyone is using a different gui that you have take some time to learn. The prisma studio looks like it has fairly light learning-curve,

**Comment by dthyresson** [comment]
@guledali While the docs do mention the Prisma CLI , you're right that these could be a Guide or How To that answers "So, I have a database, not how do I see the data?" (Not a real title).

And also the Prisma section doesn't showcase studio here: https://redwoodjs.com/docs/cli-commands#prisma

There are a few options:

* [Prisma Studi](https://www.prisma.io/studio)
* [TablePlus](https://tableplus.com)
* [Postico](https://eggerapps.at/postico/)
* [DBeaver](https://dbeaver.io)
* [Suabase Dashboard/Studio](https://supabase.com/database)
* PSQL

etc

And all are great to learn a little more SQL and to try out queries before attempting a Prisma query.

**Comment by jtoar** [comment]
We do mention it in the tutorial now! https://redwoodjs.com/docs/tutorial/chapter2/getting-dynamic#prisma-studio
